// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     100168_3.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/container"
	"github.com/actgardner/gogen-avro/v10/vm"
)

func NewEnergizationDtoWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := NewEnergizationDto()
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

// container reader
type EnergizationDtoReader struct {
	r io.Reader
	p *vm.Program
}

func NewEnergizationDtoReader(r io.Reader) (*EnergizationDtoReader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewEnergizationDto()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &EnergizationDtoReader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r EnergizationDtoReader) Read() (EnergizationDto, error) {
	t := NewEnergizationDto()
	err := vm.Eval(r.r, r.p, &t)
	return t, err
}
