// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     100257_1.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/container"
	"github.com/actgardner/gogen-avro/v10/vm"
)

func NewSpotPriceWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := NewSpotPrice()
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

// container reader
type SpotPriceReader struct {
	r io.Reader
	p *vm.Program
}

func NewSpotPriceReader(r io.Reader) (*SpotPriceReader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewSpotPrice()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &SpotPriceReader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r SpotPriceReader) Read() (SpotPrice, error) {
	t := NewSpotPrice()
	err := vm.Eval(r.r, r.p, &t)
	return t, err
}
