// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     100048_1.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/container"
	"github.com/actgardner/gogen-avro/v10/vm"
)

func NewPersonWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := NewPerson()
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

// container reader
type PersonReader struct {
	r io.Reader
	p *vm.Program
}

func NewPersonReader(r io.Reader) (*PersonReader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewPerson()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &PersonReader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r PersonReader) Read() (Person, error) {
	t := NewPerson()
	err := vm.Eval(r.r, r.p, &t)
	return t, err
}
