// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     100152_1.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

type UnionNullDummyEventHeaderTypeEnum int

const (
	UnionNullDummyEventHeaderTypeEnumDummyEventHeader UnionNullDummyEventHeaderTypeEnum = 1
)

type UnionNullDummyEventHeader struct {
	Null             *types.NullVal
	DummyEventHeader DummyEventHeader
	UnionType        UnionNullDummyEventHeaderTypeEnum
}

func writeUnionNullDummyEventHeader(r *UnionNullDummyEventHeader, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionNullDummyEventHeaderTypeEnumDummyEventHeader:
		return writeDummyEventHeader(r.DummyEventHeader, w)
	}
	return fmt.Errorf("invalid value for *UnionNullDummyEventHeader")
}

func NewUnionNullDummyEventHeader() *UnionNullDummyEventHeader {
	return &UnionNullDummyEventHeader{}
}

func (r *UnionNullDummyEventHeader) Serialize(w io.Writer) error {
	return writeUnionNullDummyEventHeader(r, w)
}

func DeserializeUnionNullDummyEventHeader(r io.Reader) (*UnionNullDummyEventHeader, error) {
	t := NewUnionNullDummyEventHeader()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func DeserializeUnionNullDummyEventHeaderFromSchema(r io.Reader, schema string) (*UnionNullDummyEventHeader, error) {
	t := NewUnionNullDummyEventHeader()
	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func (r *UnionNullDummyEventHeader) Schema() string {
	return "[\"null\",{\"fields\":[{\"default\":null,\"name\":\"EventId\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"EventName\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"Source\",\"type\":[\"null\",\"string\"]},{\"name\":\"TimeStamp\",\"type\":\"string\"}],\"name\":\"DummyEventHeader\",\"type\":\"record\"}]"
}

func (_ *UnionNullDummyEventHeader) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *UnionNullDummyEventHeader) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *UnionNullDummyEventHeader) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *UnionNullDummyEventHeader) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullDummyEventHeader) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *UnionNullDummyEventHeader) SetString(v string)  { panic("Unsupported operation") }

func (r *UnionNullDummyEventHeader) SetLong(v int64) {

	r.UnionType = (UnionNullDummyEventHeaderTypeEnum)(v)
}

func (r *UnionNullDummyEventHeader) Get(i int) types.Field {

	switch i {
	case 0:
		return r.Null
	case 1:
		r.DummyEventHeader = NewDummyEventHeader()
		return &types.Record{Target: (&r.DummyEventHeader)}
	}
	panic("Unknown field index")
}
func (_ *UnionNullDummyEventHeader) NullField(i int)                  { panic("Unsupported operation") }
func (_ *UnionNullDummyEventHeader) HintSize(i int)                   { panic("Unsupported operation") }
func (_ *UnionNullDummyEventHeader) SetDefault(i int)                 { panic("Unsupported operation") }
func (_ *UnionNullDummyEventHeader) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullDummyEventHeader) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *UnionNullDummyEventHeader) Finalize()                        {}

func (r *UnionNullDummyEventHeader) MarshalJSON() ([]byte, error) {

	if r == nil {
		return []byte("null"), nil
	}

	switch r.UnionType {
	case UnionNullDummyEventHeaderTypeEnumDummyEventHeader:
		return json.Marshal(map[string]interface{}{"Skogshorn.Drift.Common.Database.Entity.DummyEventHeader": r.DummyEventHeader})
	}
	return nil, fmt.Errorf("invalid value for *UnionNullDummyEventHeader")
}

func (r *UnionNullDummyEventHeader) UnmarshalJSON(data []byte) error {

	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if len(fields) > 1 {
		return fmt.Errorf("more than one type supplied for union")
	}
	if value, ok := fields["Skogshorn.Drift.Common.Database.Entity.DummyEventHeader"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.DummyEventHeader)
	}
	return fmt.Errorf("invalid value for *UnionNullDummyEventHeader")
}
