// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     100471_3.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

func writeArrayUnionNullEndDeviceEventDetail(r []*UnionNullEndDeviceEventDetail, w io.Writer) error {
	err := vm.WriteLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for _, e := range r {
		err = writeUnionNullEndDeviceEventDetail(e, w)
		if err != nil {
			return err
		}
	}
	return vm.WriteLong(0, w)
}

type ArrayUnionNullEndDeviceEventDetailWrapper struct {
	Target *[]*UnionNullEndDeviceEventDetail
}

func (_ ArrayUnionNullEndDeviceEventDetailWrapper) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ ArrayUnionNullEndDeviceEventDetailWrapper) SetInt(v int32)    { panic("Unsupported operation") }
func (_ ArrayUnionNullEndDeviceEventDetailWrapper) SetLong(v int64)   { panic("Unsupported operation") }
func (_ ArrayUnionNullEndDeviceEventDetailWrapper) SetFloat(v float32) {
	panic("Unsupported operation")
}
func (_ ArrayUnionNullEndDeviceEventDetailWrapper) SetDouble(v float64) {
	panic("Unsupported operation")
}
func (_ ArrayUnionNullEndDeviceEventDetailWrapper) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ ArrayUnionNullEndDeviceEventDetailWrapper) SetString(v string) {
	panic("Unsupported operation")
}
func (_ ArrayUnionNullEndDeviceEventDetailWrapper) SetUnionElem(v int64) {
	panic("Unsupported operation")
}
func (_ ArrayUnionNullEndDeviceEventDetailWrapper) Get(i int) types.Field {
	panic("Unsupported operation")
}
func (_ ArrayUnionNullEndDeviceEventDetailWrapper) AppendMap(key string) types.Field {
	panic("Unsupported operation")
}
func (_ ArrayUnionNullEndDeviceEventDetailWrapper) Finalize()        {}
func (_ ArrayUnionNullEndDeviceEventDetailWrapper) SetDefault(i int) { panic("Unsupported operation") }
func (r ArrayUnionNullEndDeviceEventDetailWrapper) HintSize(s int) {
	if len(*r.Target) == 0 {
		*r.Target = make([]*UnionNullEndDeviceEventDetail, 0, s)
	}
}
func (r ArrayUnionNullEndDeviceEventDetailWrapper) NullField(i int) {
	(*r.Target)[len(*r.Target)-1] = nil
}

func (r ArrayUnionNullEndDeviceEventDetailWrapper) AppendArray() types.Field {
	var v *UnionNullEndDeviceEventDetail
	v = NewUnionNullEndDeviceEventDetail()

	*r.Target = append(*r.Target, v)

	return (*r.Target)[len(*r.Target)-1]
}
