// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     100471_3.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

func writeArrayUnionNullEventData(r []*UnionNullEventData, w io.Writer) error {
	err := vm.WriteLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for _, e := range r {
		err = writeUnionNullEventData(e, w)
		if err != nil {
			return err
		}
	}
	return vm.WriteLong(0, w)
}

type ArrayUnionNullEventDataWrapper struct {
	Target *[]*UnionNullEventData
}

func (_ ArrayUnionNullEventDataWrapper) SetBoolean(v bool)     { panic("Unsupported operation") }
func (_ ArrayUnionNullEventDataWrapper) SetInt(v int32)        { panic("Unsupported operation") }
func (_ ArrayUnionNullEventDataWrapper) SetLong(v int64)       { panic("Unsupported operation") }
func (_ ArrayUnionNullEventDataWrapper) SetFloat(v float32)    { panic("Unsupported operation") }
func (_ ArrayUnionNullEventDataWrapper) SetDouble(v float64)   { panic("Unsupported operation") }
func (_ ArrayUnionNullEventDataWrapper) SetBytes(v []byte)     { panic("Unsupported operation") }
func (_ ArrayUnionNullEventDataWrapper) SetString(v string)    { panic("Unsupported operation") }
func (_ ArrayUnionNullEventDataWrapper) SetUnionElem(v int64)  { panic("Unsupported operation") }
func (_ ArrayUnionNullEventDataWrapper) Get(i int) types.Field { panic("Unsupported operation") }
func (_ ArrayUnionNullEventDataWrapper) AppendMap(key string) types.Field {
	panic("Unsupported operation")
}
func (_ ArrayUnionNullEventDataWrapper) Finalize()        {}
func (_ ArrayUnionNullEventDataWrapper) SetDefault(i int) { panic("Unsupported operation") }
func (r ArrayUnionNullEventDataWrapper) HintSize(s int) {
	if len(*r.Target) == 0 {
		*r.Target = make([]*UnionNullEventData, 0, s)
	}
}
func (r ArrayUnionNullEventDataWrapper) NullField(i int) {
	(*r.Target)[len(*r.Target)-1] = nil
}

func (r ArrayUnionNullEventDataWrapper) AppendArray() types.Field {
	var v *UnionNullEventData
	v = NewUnionNullEventData()

	*r.Target = append(*r.Target, v)

	return (*r.Target)[len(*r.Target)-1]
}
