// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     100471_3.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

type UnionNullMeterReadingTypeEnum int

const (
	UnionNullMeterReadingTypeEnumMeterReading UnionNullMeterReadingTypeEnum = 1
)

type UnionNullMeterReading struct {
	Null         *types.NullVal
	MeterReading MeterReading
	UnionType    UnionNullMeterReadingTypeEnum
}

func writeUnionNullMeterReading(r *UnionNullMeterReading, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionNullMeterReadingTypeEnumMeterReading:
		return writeMeterReading(r.MeterReading, w)
	}
	return fmt.Errorf("invalid value for *UnionNullMeterReading")
}

func NewUnionNullMeterReading() *UnionNullMeterReading {
	return &UnionNullMeterReading{}
}

func (r *UnionNullMeterReading) Serialize(w io.Writer) error {
	return writeUnionNullMeterReading(r, w)
}

func DeserializeUnionNullMeterReading(r io.Reader) (*UnionNullMeterReading, error) {
	t := NewUnionNullMeterReading()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func DeserializeUnionNullMeterReadingFromSchema(r io.Reader, schema string) (*UnionNullMeterReading, error) {
	t := NewUnionNullMeterReading()
	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func (r *UnionNullMeterReading) Schema() string {
	return "[\"null\",{\"fields\":[{\"default\":null,\"name\":\"Readings\",\"type\":[\"null\",{\"items\":[\"null\",{\"fields\":[{\"default\":null,\"name\":\"ReadingType\",\"type\":[\"null\",{\"fields\":[{\"default\":null,\"name\":\"ref\",\"type\":[\"null\",\"string\"]}],\"name\":\"ReadingReadingType\",\"type\":\"record\"}]},{\"default\":null,\"name\":\"value\",\"type\":[\"null\",\"string\"]}],\"name\":\"Reading\",\"type\":\"record\"}],\"type\":\"array\"}]}],\"name\":\"MeterReading\",\"type\":\"record\"}]"
}

func (_ *UnionNullMeterReading) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *UnionNullMeterReading) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *UnionNullMeterReading) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *UnionNullMeterReading) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullMeterReading) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *UnionNullMeterReading) SetString(v string)  { panic("Unsupported operation") }

func (r *UnionNullMeterReading) SetLong(v int64) {

	r.UnionType = (UnionNullMeterReadingTypeEnum)(v)
}

func (r *UnionNullMeterReading) Get(i int) types.Field {

	switch i {
	case 0:
		return r.Null
	case 1:
		r.MeterReading = NewMeterReading()
		return &types.Record{Target: (&r.MeterReading)}
	}
	panic("Unknown field index")
}
func (_ *UnionNullMeterReading) NullField(i int)                  { panic("Unsupported operation") }
func (_ *UnionNullMeterReading) HintSize(i int)                   { panic("Unsupported operation") }
func (_ *UnionNullMeterReading) SetDefault(i int)                 { panic("Unsupported operation") }
func (_ *UnionNullMeterReading) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullMeterReading) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *UnionNullMeterReading) Finalize()                        {}

func (r *UnionNullMeterReading) MarshalJSON() ([]byte, error) {

	if r == nil {
		return []byte("null"), nil
	}

	switch r.UnionType {
	case UnionNullMeterReadingTypeEnumMeterReading:
		return json.Marshal(map[string]interface{}{"MeteringeventsMsiToAdms.Eventhub.Aidon.MeterReading": r.MeterReading})
	}
	return nil, fmt.Errorf("invalid value for *UnionNullMeterReading")
}

func (r *UnionNullMeterReading) UnmarshalJSON(data []byte) error {

	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if len(fields) > 1 {
		return fmt.Errorf("more than one type supplied for union")
	}
	if value, ok := fields["MeteringeventsMsiToAdms.Eventhub.Aidon.MeterReading"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.MeterReading)
	}
	return fmt.Errorf("invalid value for *UnionNullMeterReading")
}
