// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     100471_3.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

type UnionNullReadingReadingTypeTypeEnum int

const (
	UnionNullReadingReadingTypeTypeEnumReadingReadingType UnionNullReadingReadingTypeTypeEnum = 1
)

type UnionNullReadingReadingType struct {
	Null               *types.NullVal
	ReadingReadingType ReadingReadingType
	UnionType          UnionNullReadingReadingTypeTypeEnum
}

func writeUnionNullReadingReadingType(r *UnionNullReadingReadingType, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionNullReadingReadingTypeTypeEnumReadingReadingType:
		return writeReadingReadingType(r.ReadingReadingType, w)
	}
	return fmt.Errorf("invalid value for *UnionNullReadingReadingType")
}

func NewUnionNullReadingReadingType() *UnionNullReadingReadingType {
	return &UnionNullReadingReadingType{}
}

func (r *UnionNullReadingReadingType) Serialize(w io.Writer) error {
	return writeUnionNullReadingReadingType(r, w)
}

func DeserializeUnionNullReadingReadingType(r io.Reader) (*UnionNullReadingReadingType, error) {
	t := NewUnionNullReadingReadingType()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func DeserializeUnionNullReadingReadingTypeFromSchema(r io.Reader, schema string) (*UnionNullReadingReadingType, error) {
	t := NewUnionNullReadingReadingType()
	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func (r *UnionNullReadingReadingType) Schema() string {
	return "[\"null\",{\"fields\":[{\"default\":null,\"name\":\"ref\",\"type\":[\"null\",\"string\"]}],\"name\":\"ReadingReadingType\",\"type\":\"record\"}]"
}

func (_ *UnionNullReadingReadingType) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *UnionNullReadingReadingType) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *UnionNullReadingReadingType) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *UnionNullReadingReadingType) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullReadingReadingType) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *UnionNullReadingReadingType) SetString(v string)  { panic("Unsupported operation") }

func (r *UnionNullReadingReadingType) SetLong(v int64) {

	r.UnionType = (UnionNullReadingReadingTypeTypeEnum)(v)
}

func (r *UnionNullReadingReadingType) Get(i int) types.Field {

	switch i {
	case 0:
		return r.Null
	case 1:
		r.ReadingReadingType = NewReadingReadingType()
		return &types.Record{Target: (&r.ReadingReadingType)}
	}
	panic("Unknown field index")
}
func (_ *UnionNullReadingReadingType) NullField(i int)  { panic("Unsupported operation") }
func (_ *UnionNullReadingReadingType) HintSize(i int)   { panic("Unsupported operation") }
func (_ *UnionNullReadingReadingType) SetDefault(i int) { panic("Unsupported operation") }
func (_ *UnionNullReadingReadingType) AppendMap(key string) types.Field {
	panic("Unsupported operation")
}
func (_ *UnionNullReadingReadingType) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *UnionNullReadingReadingType) Finalize()                {}

func (r *UnionNullReadingReadingType) MarshalJSON() ([]byte, error) {

	if r == nil {
		return []byte("null"), nil
	}

	switch r.UnionType {
	case UnionNullReadingReadingTypeTypeEnumReadingReadingType:
		return json.Marshal(map[string]interface{}{"MeteringeventsMsiToAdms.Eventhub.Aidon.ReadingReadingType": r.ReadingReadingType})
	}
	return nil, fmt.Errorf("invalid value for *UnionNullReadingReadingType")
}

func (r *UnionNullReadingReadingType) UnmarshalJSON(data []byte) error {

	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if len(fields) > 1 {
		return fmt.Errorf("more than one type supplied for union")
	}
	if value, ok := fields["MeteringeventsMsiToAdms.Eventhub.Aidon.ReadingReadingType"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.ReadingReadingType)
	}
	return fmt.Errorf("invalid value for *UnionNullReadingReadingType")
}
