// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     100471_3.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

type UnionNullArrayUnionNullReadingTypeEnum int

const (
	UnionNullArrayUnionNullReadingTypeEnumArrayUnionNullReading UnionNullArrayUnionNullReadingTypeEnum = 1
)

type UnionNullArrayUnionNullReading struct {
	Null                  *types.NullVal
	ArrayUnionNullReading []*UnionNullReading
	UnionType             UnionNullArrayUnionNullReadingTypeEnum
}

func writeUnionNullArrayUnionNullReading(r *UnionNullArrayUnionNullReading, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionNullArrayUnionNullReadingTypeEnumArrayUnionNullReading:
		return writeArrayUnionNullReading(r.ArrayUnionNullReading, w)
	}
	return fmt.Errorf("invalid value for *UnionNullArrayUnionNullReading")
}

func NewUnionNullArrayUnionNullReading() *UnionNullArrayUnionNullReading {
	return &UnionNullArrayUnionNullReading{}
}

func (r *UnionNullArrayUnionNullReading) Serialize(w io.Writer) error {
	return writeUnionNullArrayUnionNullReading(r, w)
}

func DeserializeUnionNullArrayUnionNullReading(r io.Reader) (*UnionNullArrayUnionNullReading, error) {
	t := NewUnionNullArrayUnionNullReading()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func DeserializeUnionNullArrayUnionNullReadingFromSchema(r io.Reader, schema string) (*UnionNullArrayUnionNullReading, error) {
	t := NewUnionNullArrayUnionNullReading()
	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func (r *UnionNullArrayUnionNullReading) Schema() string {
	return "[\"null\",{\"items\":[\"null\",{\"fields\":[{\"default\":null,\"name\":\"ReadingType\",\"type\":[\"null\",{\"fields\":[{\"default\":null,\"name\":\"ref\",\"type\":[\"null\",\"string\"]}],\"name\":\"ReadingReadingType\",\"type\":\"record\"}]},{\"default\":null,\"name\":\"value\",\"type\":[\"null\",\"string\"]}],\"name\":\"Reading\",\"type\":\"record\"}],\"type\":\"array\"}]"
}

func (_ *UnionNullArrayUnionNullReading) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *UnionNullArrayUnionNullReading) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *UnionNullArrayUnionNullReading) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *UnionNullArrayUnionNullReading) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullArrayUnionNullReading) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *UnionNullArrayUnionNullReading) SetString(v string)  { panic("Unsupported operation") }

func (r *UnionNullArrayUnionNullReading) SetLong(v int64) {

	r.UnionType = (UnionNullArrayUnionNullReadingTypeEnum)(v)
}

func (r *UnionNullArrayUnionNullReading) Get(i int) types.Field {

	switch i {
	case 0:
		return r.Null
	case 1:
		r.ArrayUnionNullReading = make([]*UnionNullReading, 0)
		return &ArrayUnionNullReadingWrapper{Target: (&r.ArrayUnionNullReading)}
	}
	panic("Unknown field index")
}
func (_ *UnionNullArrayUnionNullReading) NullField(i int)  { panic("Unsupported operation") }
func (_ *UnionNullArrayUnionNullReading) HintSize(i int)   { panic("Unsupported operation") }
func (_ *UnionNullArrayUnionNullReading) SetDefault(i int) { panic("Unsupported operation") }
func (_ *UnionNullArrayUnionNullReading) AppendMap(key string) types.Field {
	panic("Unsupported operation")
}
func (_ *UnionNullArrayUnionNullReading) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *UnionNullArrayUnionNullReading) Finalize()                {}

func (r *UnionNullArrayUnionNullReading) MarshalJSON() ([]byte, error) {

	if r == nil {
		return []byte("null"), nil
	}

	switch r.UnionType {
	case UnionNullArrayUnionNullReadingTypeEnumArrayUnionNullReading:
		return json.Marshal(map[string]interface{}{"array": r.ArrayUnionNullReading})
	}
	return nil, fmt.Errorf("invalid value for *UnionNullArrayUnionNullReading")
}

func (r *UnionNullArrayUnionNullReading) UnmarshalJSON(data []byte) error {

	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if len(fields) > 1 {
		return fmt.Errorf("more than one type supplied for union")
	}
	if value, ok := fields["array"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.ArrayUnionNullReading)
	}
	return fmt.Errorf("invalid value for *UnionNullArrayUnionNullReading")
}
