// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     100471_3.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

type UnionNullArrayUnionNullEndDeviceEventDetailTypeEnum int

const (
	UnionNullArrayUnionNullEndDeviceEventDetailTypeEnumArrayUnionNullEndDeviceEventDetail UnionNullArrayUnionNullEndDeviceEventDetailTypeEnum = 1
)

type UnionNullArrayUnionNullEndDeviceEventDetail struct {
	Null                               *types.NullVal
	ArrayUnionNullEndDeviceEventDetail []*UnionNullEndDeviceEventDetail
	UnionType                          UnionNullArrayUnionNullEndDeviceEventDetailTypeEnum
}

func writeUnionNullArrayUnionNullEndDeviceEventDetail(r *UnionNullArrayUnionNullEndDeviceEventDetail, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionNullArrayUnionNullEndDeviceEventDetailTypeEnumArrayUnionNullEndDeviceEventDetail:
		return writeArrayUnionNullEndDeviceEventDetail(r.ArrayUnionNullEndDeviceEventDetail, w)
	}
	return fmt.Errorf("invalid value for *UnionNullArrayUnionNullEndDeviceEventDetail")
}

func NewUnionNullArrayUnionNullEndDeviceEventDetail() *UnionNullArrayUnionNullEndDeviceEventDetail {
	return &UnionNullArrayUnionNullEndDeviceEventDetail{}
}

func (r *UnionNullArrayUnionNullEndDeviceEventDetail) Serialize(w io.Writer) error {
	return writeUnionNullArrayUnionNullEndDeviceEventDetail(r, w)
}

func DeserializeUnionNullArrayUnionNullEndDeviceEventDetail(r io.Reader) (*UnionNullArrayUnionNullEndDeviceEventDetail, error) {
	t := NewUnionNullArrayUnionNullEndDeviceEventDetail()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func DeserializeUnionNullArrayUnionNullEndDeviceEventDetailFromSchema(r io.Reader, schema string) (*UnionNullArrayUnionNullEndDeviceEventDetail, error) {
	t := NewUnionNullArrayUnionNullEndDeviceEventDetail()
	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func (r *UnionNullArrayUnionNullEndDeviceEventDetail) Schema() string {
	return "[\"null\",{\"items\":[\"null\",{\"fields\":[{\"default\":null,\"name\":\"name\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"value\",\"type\":[\"null\",\"string\"]}],\"name\":\"EndDeviceEventDetail\",\"type\":\"record\"}],\"type\":\"array\"}]"
}

func (_ *UnionNullArrayUnionNullEndDeviceEventDetail) SetBoolean(v bool) {
	panic("Unsupported operation")
}
func (_ *UnionNullArrayUnionNullEndDeviceEventDetail) SetInt(v int32) { panic("Unsupported operation") }
func (_ *UnionNullArrayUnionNullEndDeviceEventDetail) SetFloat(v float32) {
	panic("Unsupported operation")
}
func (_ *UnionNullArrayUnionNullEndDeviceEventDetail) SetDouble(v float64) {
	panic("Unsupported operation")
}
func (_ *UnionNullArrayUnionNullEndDeviceEventDetail) SetBytes(v []byte) {
	panic("Unsupported operation")
}
func (_ *UnionNullArrayUnionNullEndDeviceEventDetail) SetString(v string) {
	panic("Unsupported operation")
}

func (r *UnionNullArrayUnionNullEndDeviceEventDetail) SetLong(v int64) {

	r.UnionType = (UnionNullArrayUnionNullEndDeviceEventDetailTypeEnum)(v)
}

func (r *UnionNullArrayUnionNullEndDeviceEventDetail) Get(i int) types.Field {

	switch i {
	case 0:
		return r.Null
	case 1:
		r.ArrayUnionNullEndDeviceEventDetail = make([]*UnionNullEndDeviceEventDetail, 0)
		return &ArrayUnionNullEndDeviceEventDetailWrapper{Target: (&r.ArrayUnionNullEndDeviceEventDetail)}
	}
	panic("Unknown field index")
}
func (_ *UnionNullArrayUnionNullEndDeviceEventDetail) NullField(i int) {
	panic("Unsupported operation")
}
func (_ *UnionNullArrayUnionNullEndDeviceEventDetail) HintSize(i int) { panic("Unsupported operation") }
func (_ *UnionNullArrayUnionNullEndDeviceEventDetail) SetDefault(i int) {
	panic("Unsupported operation")
}
func (_ *UnionNullArrayUnionNullEndDeviceEventDetail) AppendMap(key string) types.Field {
	panic("Unsupported operation")
}
func (_ *UnionNullArrayUnionNullEndDeviceEventDetail) AppendArray() types.Field {
	panic("Unsupported operation")
}
func (_ *UnionNullArrayUnionNullEndDeviceEventDetail) Finalize() {}

func (r *UnionNullArrayUnionNullEndDeviceEventDetail) MarshalJSON() ([]byte, error) {

	if r == nil {
		return []byte("null"), nil
	}

	switch r.UnionType {
	case UnionNullArrayUnionNullEndDeviceEventDetailTypeEnumArrayUnionNullEndDeviceEventDetail:
		return json.Marshal(map[string]interface{}{"array": r.ArrayUnionNullEndDeviceEventDetail})
	}
	return nil, fmt.Errorf("invalid value for *UnionNullArrayUnionNullEndDeviceEventDetail")
}

func (r *UnionNullArrayUnionNullEndDeviceEventDetail) UnmarshalJSON(data []byte) error {

	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if len(fields) > 1 {
		return fmt.Errorf("more than one type supplied for union")
	}
	if value, ok := fields["array"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.ArrayUnionNullEndDeviceEventDetail)
	}
	return fmt.Errorf("invalid value for *UnionNullArrayUnionNullEndDeviceEventDetail")
}
