// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     100487_5.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

type UnionNullArrayUnionNullWorkTimeScheduleDtoTypeEnum int

const (
	UnionNullArrayUnionNullWorkTimeScheduleDtoTypeEnumArrayUnionNullWorkTimeScheduleDto UnionNullArrayUnionNullWorkTimeScheduleDtoTypeEnum = 1
)

type UnionNullArrayUnionNullWorkTimeScheduleDto struct {
	Null                              *types.NullVal
	ArrayUnionNullWorkTimeScheduleDto []*UnionNullWorkTimeScheduleDto
	UnionType                         UnionNullArrayUnionNullWorkTimeScheduleDtoTypeEnum
}

func writeUnionNullArrayUnionNullWorkTimeScheduleDto(r *UnionNullArrayUnionNullWorkTimeScheduleDto, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionNullArrayUnionNullWorkTimeScheduleDtoTypeEnumArrayUnionNullWorkTimeScheduleDto:
		return writeArrayUnionNullWorkTimeScheduleDto(r.ArrayUnionNullWorkTimeScheduleDto, w)
	}
	return fmt.Errorf("invalid value for *UnionNullArrayUnionNullWorkTimeScheduleDto")
}

func NewUnionNullArrayUnionNullWorkTimeScheduleDto() *UnionNullArrayUnionNullWorkTimeScheduleDto {
	return &UnionNullArrayUnionNullWorkTimeScheduleDto{}
}

func (r *UnionNullArrayUnionNullWorkTimeScheduleDto) Serialize(w io.Writer) error {
	return writeUnionNullArrayUnionNullWorkTimeScheduleDto(r, w)
}

func DeserializeUnionNullArrayUnionNullWorkTimeScheduleDto(r io.Reader) (*UnionNullArrayUnionNullWorkTimeScheduleDto, error) {
	t := NewUnionNullArrayUnionNullWorkTimeScheduleDto()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func DeserializeUnionNullArrayUnionNullWorkTimeScheduleDtoFromSchema(r io.Reader, schema string) (*UnionNullArrayUnionNullWorkTimeScheduleDto, error) {
	t := NewUnionNullArrayUnionNullWorkTimeScheduleDto()
	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func (r *UnionNullArrayUnionNullWorkTimeScheduleDto) Schema() string {
	return "[\"null\",{\"items\":[\"null\",{\"fields\":[{\"default\":null,\"name\":\"kind\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"scheduleInterval\",\"type\":[\"null\",{\"fields\":[{\"default\":null,\"name\":\"end\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"endSpecified\",\"type\":[\"null\",\"boolean\"]},{\"default\":null,\"name\":\"start\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"startSpecified\",\"type\":[\"null\",\"boolean\"]}],\"name\":\"WorkTimeScheduleScheduleIntervalDto\",\"type\":\"record\"}]}],\"name\":\"WorkTimeScheduleDto\",\"type\":\"record\"}],\"type\":\"array\"}]"
}

func (_ *UnionNullArrayUnionNullWorkTimeScheduleDto) SetBoolean(v bool) {
	panic("Unsupported operation")
}
func (_ *UnionNullArrayUnionNullWorkTimeScheduleDto) SetInt(v int32) { panic("Unsupported operation") }
func (_ *UnionNullArrayUnionNullWorkTimeScheduleDto) SetFloat(v float32) {
	panic("Unsupported operation")
}
func (_ *UnionNullArrayUnionNullWorkTimeScheduleDto) SetDouble(v float64) {
	panic("Unsupported operation")
}
func (_ *UnionNullArrayUnionNullWorkTimeScheduleDto) SetBytes(v []byte) {
	panic("Unsupported operation")
}
func (_ *UnionNullArrayUnionNullWorkTimeScheduleDto) SetString(v string) {
	panic("Unsupported operation")
}

func (r *UnionNullArrayUnionNullWorkTimeScheduleDto) SetLong(v int64) {

	r.UnionType = (UnionNullArrayUnionNullWorkTimeScheduleDtoTypeEnum)(v)
}

func (r *UnionNullArrayUnionNullWorkTimeScheduleDto) Get(i int) types.Field {

	switch i {
	case 0:
		return r.Null
	case 1:
		r.ArrayUnionNullWorkTimeScheduleDto = make([]*UnionNullWorkTimeScheduleDto, 0)
		return &ArrayUnionNullWorkTimeScheduleDtoWrapper{Target: (&r.ArrayUnionNullWorkTimeScheduleDto)}
	}
	panic("Unknown field index")
}
func (_ *UnionNullArrayUnionNullWorkTimeScheduleDto) NullField(i int) { panic("Unsupported operation") }
func (_ *UnionNullArrayUnionNullWorkTimeScheduleDto) HintSize(i int)  { panic("Unsupported operation") }
func (_ *UnionNullArrayUnionNullWorkTimeScheduleDto) SetDefault(i int) {
	panic("Unsupported operation")
}
func (_ *UnionNullArrayUnionNullWorkTimeScheduleDto) AppendMap(key string) types.Field {
	panic("Unsupported operation")
}
func (_ *UnionNullArrayUnionNullWorkTimeScheduleDto) AppendArray() types.Field {
	panic("Unsupported operation")
}
func (_ *UnionNullArrayUnionNullWorkTimeScheduleDto) Finalize() {}

func (r *UnionNullArrayUnionNullWorkTimeScheduleDto) MarshalJSON() ([]byte, error) {

	if r == nil {
		return []byte("null"), nil
	}

	switch r.UnionType {
	case UnionNullArrayUnionNullWorkTimeScheduleDtoTypeEnumArrayUnionNullWorkTimeScheduleDto:
		return json.Marshal(map[string]interface{}{"array": r.ArrayUnionNullWorkTimeScheduleDto})
	}
	return nil, fmt.Errorf("invalid value for *UnionNullArrayUnionNullWorkTimeScheduleDto")
}

func (r *UnionNullArrayUnionNullWorkTimeScheduleDto) UnmarshalJSON(data []byte) error {

	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if len(fields) > 1 {
		return fmt.Errorf("more than one type supplied for union")
	}
	if value, ok := fields["array"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.ArrayUnionNullWorkTimeScheduleDto)
	}
	return fmt.Errorf("invalid value for *UnionNullArrayUnionNullWorkTimeScheduleDto")
}
