package schemas

//go:generate $GOPATH/bin/gogen-avro -containers rry_enum_default_test ./avsc/100448_3.avsc
//go:generate $GOPATH/bin/gogen-avro -containers dp/functionobjectchangedevent ./avsc/100135_2.avsc
//go:generate $GOPATH/bin/gogen-avro -containers dp/examples ./avsc/100044_3.avsc
//go:generate $GOPATH/bin/gogen-avro -containers kunde/convey/job ./avsc/100093_2.avsc
//go:generate $GOPATH/bin/gogen-avro -containers msi/meteringpointversions ./avsc/100058_21.avsc
//go:generate $GOPATH/bin/gogen-avro -containers no/elvia/dp/securityauditlog ./avsc/100020_1.avsc
//go:generate $GOPATH/bin/gogen-avro -containers pksqlc_m89mxdp_examples_with_name ./avsc/100062_2.avsc
//go:generate $GOPATH/bin/gogen-avro -containers pksqlc_m89mxnames ./avsc/100068_2.avsc
//go:generate $GOPATH/bin/gogen-avro -containers dp/private/edna/avroschemaexample ./avsc/100048_1.avsc
//go:generate $GOPATH/bin/gogen-avro -containers dp/private/edna/compatibility ./avsc/100057_4.avsc
//go:generate $GOPATH/bin/gogen-avro -containers dp/private/edna/examples ./avsc/100172_6.avsc
//go:generate $GOPATH/bin/gogen-avro -containers dp/private/edna/examples/oracletrial ./avsc/100112_1.avsc
//go:generate $GOPATH/bin/gogen-avro -containers dp/private/edna/examplesz ./avsc/100112_1.avsc
//go:generate $GOPATH/bin/gogen-avro -containers dp/private/edna/examplesx ./avsc/100112_1.avsc
//go:generate $GOPATH/bin/gogen-avro -containers dp/private/edna/integrationtesting ./avsc/100189_1.avsc
//go:generate $GOPATH/bin/gogen-avro -containers dp/private/uniqueid/identifiedobject ./avsc/100254_5.avsc
//go:generate $GOPATH/bin/gogen-avro -containers edna/private/events/integrationtest1 ./avsc/100150_1.avsc
//go:generate $GOPATH/bin/gogen-avro -containers edna/private/events/integrationtest2 ./avsc/100150_1.avsc
//go:generate $GOPATH/bin/gogen-avro -containers kunde/private/afiextensions/invoiceagreementevents ./avsc/100398_5.avsc
//go:generate $GOPATH/bin/gogen-avro -containers kunde/private/afiextensions/invoicebalanceevents ./avsc/100363_1.avsc
//go:generate $GOPATH/bin/gogen-avro -containers kunde/private/afiextensions/invoicecreatedevents ./avsc/100396_4.avsc
//go:generate $GOPATH/bin/gogen-avro -containers kunde/private/afiextensions/invoicecreatedevents_header ./avsc/100397_2.avsc
//go:generate $GOPATH/bin/gogen-avro -containers kunde/private/afiextensions/invoicedebtcollectionevents ./avsc/100395_1.avsc
//go:generate $GOPATH/bin/gogen-avro -containers kunde/private/afiextensions/invoicepostedevents ./avsc/100443_1.avsc
//go:generate $GOPATH/bin/gogen-avro -containers kunde/private/afiextensions/salesorderevents ./avsc/100366_4.avsc
//go:generate $GOPATH/bin/gogen-avro -containers kunde/private/afiextensions/tariffevents ./avsc/100444_4.avsc
//go:generate $GOPATH/bin/gogen-avro -containers kunde/private/afiextensions/tariffsaleevents ./avsc/100346_2.avsc
//go:generate $GOPATH/bin/gogen-avro -containers kunde/private/gridtariff/maxconsumption ./avsc/100244_2.avsc
//go:generate $GOPATH/bin/gogen-avro -containers kunde/private/gridtariff/meteringpointtariffs ./avsc/100285_4.avsc
//go:generate $GOPATH/bin/gogen-avro -containers kunde/private/gridtariff/prices ./avsc/100242_2.avsc
//go:generate $GOPATH/bin/gogen-avro -containers kunde/private/kunde/contractaccesses ./avsc/100412_1.avsc
//go:generate $GOPATH/bin/gogen-avro -containers kunde/private/kunde/contractproduct ./avsc/100406_1.avsc
//go:generate $GOPATH/bin/gogen-avro -containers kunde/private/kunde/contractproducts ./avsc/100408_3.avsc
//go:generate $GOPATH/bin/gogen-avro -containers kunde/private/kunde/hanports ./avsc/100441_1.avsc
//go:generate $GOPATH/bin/gogen-avro -containers kunde/private/kunde/powersuppliers ./avsc/100388_2.avsc
//go:generate $GOPATH/bin/gogen-avro -containers kunde/private/kunde/spotprice_dayahead ./avsc/100257_1.avsc
//go:generate $GOPATH/bin/gogen-avro -containers msi/private/mdmx/annualconsumptions ./avsc/100177_1.avsc
//go:generate $GOPATH/bin/gogen-avro -containers dk/public/adms_extensions/bulkdigitaltelemetry ./avsc/100361_4.avsc
//go:generate $GOPATH/bin/gogen-avro -containers dk/public/adms_extensions/customernotification ./avsc/100375_2.avsc
//go:generate $GOPATH/bin/gogen-avro -containers dk/public/adms_extensions/energization_status ./avsc/100168_3.avsc
//go:generate $GOPATH/bin/gogen-avro -containers dk/public/adms_extensions/maintenanceorder ./avsc/100487_5.avsc
//go:generate $GOPATH/bin/gogen-avro -containers dk/public/adms_extensions/message_status ./avsc/100423_3.avsc
//go:generate $GOPATH/bin/gogen-avro -containers dk/public/adms_extensions/substation_short_circuit_events ./avsc/100471_3.avsc
//go:generate $GOPATH/bin/gogen-avro -containers dk/public/adms_extensions/switchingplans ./avsc/100486_7.avsc
//go:generate $GOPATH/bin/gogen-avro -containers dk/public/adms/analogs ./avsc/100493_1.avsc
//go:generate $GOPATH/bin/gogen-avro -containers dk/public/adms/discretes ./avsc/100492_3.avsc
//go:generate $GOPATH/bin/gogen-avro -containers dk/public/iss/test ./avsc/100112_1.avsc
//go:generate $GOPATH/bin/gogen-avro -containers dk/public/lvis_extensions/low_voltage_outage_events ./avsc/100458_1.avsc
//go:generate $GOPATH/bin/gogen-avro -containers dk/public/lvis_extensions/message_status ./avsc/100423_1.avsc
//go:generate $GOPATH/bin/gogen-avro -containers dp/public/convey/events ./avsc/100279_6.avsc
//go:generate $GOPATH/bin/gogen-avro -containers dp/public/core/drifthendelser ./avsc/100152_1.avsc
//go:generate $GOPATH/bin/gogen-avro -containers dp/public/core/ifshendelser ./avsc/100136_1.avsc
//go:generate $GOPATH/bin/gogen-avro -containers dp/public/core/kundehendelser ./avsc/100159_3.avsc
//go:generate $GOPATH/bin/gogen-avro -containers dp/public/core/mymodel ./avsc/100154_2.avsc
//go:generate $GOPATH/bin/gogen-avro -containers dp/public/core/netthendelser ./avsc/100147_1.avsc
//go:generate $GOPATH/bin/gogen-avro -containers dp/public/lvis_extensions/message_status ./avsc/100423_1.avsc
//go:generate $GOPATH/bin/gogen-avro -containers dp/public/lvis_extensions/meterstatus_request ./avsc/100419_2.avsc
//go:generate $GOPATH/bin/gogen-avro -containers dp/public/lvis_extensions/outageevents ./avsc/100450_1.avsc
//go:generate $GOPATH/bin/gogen-avro -containers dp/public/skogshorn/drifthendelser ./avsc/100126_1.avsc
//go:generate $GOPATH/bin/gogen-avro -containers dp/public/skogshorn/ifshendelser ./avsc/100136_7.avsc
//go:generate $GOPATH/bin/gogen-avro -containers dp/public/skogshorn/kundehendelser ./avsc/100125_1.avsc
//go:generate $GOPATH/bin/gogen-avro -containers dp/public/skogshorn/msihendelser ./avsc/100124_1.avsc
//go:generate $GOPATH/bin/gogen-avro -containers dp/public/skogshorn/netthendelser ./avsc/100147_24.avsc
//go:generate $GOPATH/bin/gogen-avro -containers kunde/public/convey/job ./avsc/100093_1.avsc
//go:generate $GOPATH/bin/gogen-avro -containers kunde/public/elwinextensions/workorders ./avsc/100236_8.avsc
//go:generate $GOPATH/bin/gogen-avro -containers kunde/public/gridtariff/meteringpointtariffs ./avsc/100181_1.avsc
//go:generate $GOPATH/bin/gogen-avro -containers kunde/public/gridtariff/meteringpointtariffss ./avsc/100181_1.avsc
//go:generate $GOPATH/bin/gogen-avro -containers kunde/public/kunde_extensions/createdtroubledticket ./avsc/100467_3.avsc
//go:generate $GOPATH/bin/gogen-avro -containers kunde/public/kunde_extensions/dialogue ./avsc/100238_6.avsc
//go:generate $GOPATH/bin/gogen-avro -containers kunde/public/kunde_extensions/internaldialogue ./avsc/100207_1.avsc
//go:generate $GOPATH/bin/gogen-avro -containers kunde/public/kunde_extensions/workorder_poc ./avsc/100182_1.avsc
//go:generate $GOPATH/bin/gogen-avro -containers kunde/public/kunde_extensions/workorders ./avsc/100250_7.avsc
//go:generate $GOPATH/bin/gogen-avro -containers kunde/public/mmm/anleggsbestillinger ./avsc/100349_1.avsc
//go:generate $GOPATH/bin/gogen-avro -containers kunde/public/mmm/fakturahendelser ./avsc/100372_1.avsc
//go:generate $GOPATH/bin/gogen-avro -containers kunde/public/mmm/nettleieavtalehendelser ./avsc/100480_13.avsc
//go:generate $GOPATH/bin/gogen-avro -containers kunde/public/mmm/nettleieavtaler ./avsc/100479_10.avsc
//go:generate $GOPATH/bin/gogen-avro -containers kunde/public/mmm/nettleieavtaler_elhubavvist ./avsc/100432_1.avsc
//go:generate $GOPATH/bin/gogen-avro -containers kunde/public/mmm/nettleiecontractevents ./avsc/100251_9.avsc
