// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     100423_3.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type MessageStatus int32

const (
	MessageStatusCouldNotSendToSaf    MessageStatus = 0
	MessageStatusSentToSaf            MessageStatus = 1
	MessageStatusReceivedOkFromSaf    MessageStatus = 2
	MessageStatusReceivedErrorFromSaf MessageStatus = 3
)

func (e MessageStatus) String() string {
	switch e {
	case MessageStatusCouldNotSendToSaf:
		return "CouldNotSendToSaf"
	case MessageStatusSentToSaf:
		return "SentToSaf"
	case MessageStatusReceivedOkFromSaf:
		return "ReceivedOkFromSaf"
	case MessageStatusReceivedErrorFromSaf:
		return "ReceivedErrorFromSaf"
	}
	return "unknown"
}

func writeMessageStatus(r MessageStatus, w io.Writer) error {
	return vm.WriteInt(int32(r), w)
}

func NewMessageStatusValue(raw string) (r MessageStatus, err error) {
	switch raw {
	case "CouldNotSendToSaf":
		return MessageStatusCouldNotSendToSaf, nil
	case "SentToSaf":
		return MessageStatusSentToSaf, nil
	case "ReceivedOkFromSaf":
		return MessageStatusReceivedOkFromSaf, nil
	case "ReceivedErrorFromSaf":
		return MessageStatusReceivedErrorFromSaf, nil
	}

	return -1, fmt.Errorf("invalid value for MessageStatus: '%s'", raw)

}

func (b MessageStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(b.String())
}

func (b *MessageStatus) UnmarshalJSON(data []byte) error {
	var stringVal string
	err := json.Unmarshal(data, &stringVal)
	if err != nil {
		return err
	}
	val, err := NewMessageStatusValue(stringVal)
	*b = val
	return err
}

type MessageStatusWrapper struct {
	Target *MessageStatus
}

func (b MessageStatusWrapper) SetBoolean(v bool) {
	panic("Unable to assign boolean to int field")
}

func (b MessageStatusWrapper) SetInt(v int32) {
	*(b.Target) = MessageStatus(v)
}

func (b MessageStatusWrapper) SetLong(v int64) {
	panic("Unable to assign long to int field")
}

func (b MessageStatusWrapper) SetFloat(v float32) {
	panic("Unable to assign float to int field")
}

func (b MessageStatusWrapper) SetUnionElem(v int64) {
	panic("Unable to assign union elem to int field")
}

func (b MessageStatusWrapper) SetDouble(v float64) {
	panic("Unable to assign double to int field")
}

func (b MessageStatusWrapper) SetBytes(v []byte) {
	panic("Unable to assign bytes to int field")
}

func (b MessageStatusWrapper) SetString(v string) {
	panic("Unable to assign string to int field")
}

func (b MessageStatusWrapper) Get(i int) types.Field {
	panic("Unable to get field from int field")
}

func (b MessageStatusWrapper) SetDefault(i int) {
	panic("Unable to set default on int field")
}

func (b MessageStatusWrapper) AppendMap(key string) types.Field {
	panic("Unable to append map key to from int field")
}

func (b MessageStatusWrapper) AppendArray() types.Field {
	panic("Unable to append array element to from int field")
}

func (b MessageStatusWrapper) NullField(int) {
	panic("Unable to null field in int field")
}

func (b MessageStatusWrapper) HintSize(int) {
	panic("Unable to hint size in int field")
}

func (b MessageStatusWrapper) Finalize() {}
