// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     100251_9.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/container"
	"github.com/actgardner/gogen-avro/v10/vm"
)

func NewCustomerChangedWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := NewCustomerChanged()
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

// container reader
type CustomerChangedReader struct {
	r io.Reader
	p *vm.Program
}

func NewCustomerChangedReader(r io.Reader) (*CustomerChangedReader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewCustomerChanged()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &CustomerChangedReader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r CustomerChangedReader) Read() (CustomerChanged, error) {
	t := NewCustomerChanged()
	err := vm.Eval(r.r, r.p, &t)
	return t, err
}
