// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     100397_2.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

type UnionNullMoneyTypeEnum int

const (
	UnionNullMoneyTypeEnumMoney UnionNullMoneyTypeEnum = 1
)

type UnionNullMoney struct {
	Null      *types.NullVal
	Money     Money
	UnionType UnionNullMoneyTypeEnum
}

func writeUnionNullMoney(r *UnionNullMoney, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionNullMoneyTypeEnumMoney:
		return writeMoney(r.Money, w)
	}
	return fmt.Errorf("invalid value for *UnionNullMoney")
}

func NewUnionNullMoney() *UnionNullMoney {
	return &UnionNullMoney{}
}

func (r *UnionNullMoney) Serialize(w io.Writer) error {
	return writeUnionNullMoney(r, w)
}

func DeserializeUnionNullMoney(r io.Reader) (*UnionNullMoney, error) {
	t := NewUnionNullMoney()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func DeserializeUnionNullMoneyFromSchema(r io.Reader, schema string) (*UnionNullMoney, error) {
	t := NewUnionNullMoney()
	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func (r *UnionNullMoney) Schema() string {
	return "[\"null\",{\"fields\":[{\"name\":\"Amount\",\"type\":{\"logicalType\":\"decimal\",\"precision\":29,\"scale\":14,\"type\":\"bytes\"}},{\"name\":\"CurrencyCode\",\"type\":\"string\"}],\"name\":\"Money\",\"type\":\"record\"}]"
}

func (_ *UnionNullMoney) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *UnionNullMoney) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *UnionNullMoney) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *UnionNullMoney) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullMoney) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *UnionNullMoney) SetString(v string)  { panic("Unsupported operation") }

func (r *UnionNullMoney) SetLong(v int64) {

	r.UnionType = (UnionNullMoneyTypeEnum)(v)
}

func (r *UnionNullMoney) Get(i int) types.Field {

	switch i {
	case 0:
		return r.Null
	case 1:
		r.Money = NewMoney()
		return &types.Record{Target: (&r.Money)}
	}
	panic("Unknown field index")
}
func (_ *UnionNullMoney) NullField(i int)                  { panic("Unsupported operation") }
func (_ *UnionNullMoney) HintSize(i int)                   { panic("Unsupported operation") }
func (_ *UnionNullMoney) SetDefault(i int)                 { panic("Unsupported operation") }
func (_ *UnionNullMoney) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullMoney) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *UnionNullMoney) Finalize()                        {}

func (r *UnionNullMoney) MarshalJSON() ([]byte, error) {

	if r == nil {
		return []byte("null"), nil
	}

	switch r.UnionType {
	case UnionNullMoneyTypeEnumMoney:
		return json.Marshal(map[string]interface{}{"Afiextensions.Schemas.InvoiceCreatedEvents.V1.Money": r.Money})
	}
	return nil, fmt.Errorf("invalid value for *UnionNullMoney")
}

func (r *UnionNullMoney) UnmarshalJSON(data []byte) error {

	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if len(fields) > 1 {
		return fmt.Errorf("more than one type supplied for union")
	}
	if value, ok := fields["Afiextensions.Schemas.InvoiceCreatedEvents.V1.Money"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.Money)
	}
	return fmt.Errorf("invalid value for *UnionNullMoney")
}
