// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     100349_1.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/container"
	"github.com/actgardner/gogen-avro/v10/vm"
)

func NewAnleggsbestillingWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := NewAnleggsbestilling()
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

// container reader
type AnleggsbestillingReader struct {
	r io.Reader
	p *vm.Program
}

func NewAnleggsbestillingReader(r io.Reader) (*AnleggsbestillingReader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewAnleggsbestilling()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &AnleggsbestillingReader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r AnleggsbestillingReader) Read() (Anleggsbestilling, error) {
	t := NewAnleggsbestilling()
	err := vm.Eval(r.r, r.p, &t)
	return t, err
}
