// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     100375_2.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

func writeArrayUnionNullCustomerNotificationTypeCustomerNotificationDto(r []*UnionNullCustomerNotificationTypeCustomerNotificationDto, w io.Writer) error {
	err := vm.WriteLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for _, e := range r {
		err = writeUnionNullCustomerNotificationTypeCustomerNotificationDto(e, w)
		if err != nil {
			return err
		}
	}
	return vm.WriteLong(0, w)
}

type ArrayUnionNullCustomerNotificationTypeCustomerNotificationDtoWrapper struct {
	Target *[]*UnionNullCustomerNotificationTypeCustomerNotificationDto
}

func (_ ArrayUnionNullCustomerNotificationTypeCustomerNotificationDtoWrapper) SetBoolean(v bool) {
	panic("Unsupported operation")
}
func (_ ArrayUnionNullCustomerNotificationTypeCustomerNotificationDtoWrapper) SetInt(v int32) {
	panic("Unsupported operation")
}
func (_ ArrayUnionNullCustomerNotificationTypeCustomerNotificationDtoWrapper) SetLong(v int64) {
	panic("Unsupported operation")
}
func (_ ArrayUnionNullCustomerNotificationTypeCustomerNotificationDtoWrapper) SetFloat(v float32) {
	panic("Unsupported operation")
}
func (_ ArrayUnionNullCustomerNotificationTypeCustomerNotificationDtoWrapper) SetDouble(v float64) {
	panic("Unsupported operation")
}
func (_ ArrayUnionNullCustomerNotificationTypeCustomerNotificationDtoWrapper) SetBytes(v []byte) {
	panic("Unsupported operation")
}
func (_ ArrayUnionNullCustomerNotificationTypeCustomerNotificationDtoWrapper) SetString(v string) {
	panic("Unsupported operation")
}
func (_ ArrayUnionNullCustomerNotificationTypeCustomerNotificationDtoWrapper) SetUnionElem(v int64) {
	panic("Unsupported operation")
}
func (_ ArrayUnionNullCustomerNotificationTypeCustomerNotificationDtoWrapper) Get(i int) types.Field {
	panic("Unsupported operation")
}
func (_ ArrayUnionNullCustomerNotificationTypeCustomerNotificationDtoWrapper) AppendMap(key string) types.Field {
	panic("Unsupported operation")
}
func (_ ArrayUnionNullCustomerNotificationTypeCustomerNotificationDtoWrapper) Finalize() {}
func (_ ArrayUnionNullCustomerNotificationTypeCustomerNotificationDtoWrapper) SetDefault(i int) {
	panic("Unsupported operation")
}
func (r ArrayUnionNullCustomerNotificationTypeCustomerNotificationDtoWrapper) HintSize(s int) {
	if len(*r.Target) == 0 {
		*r.Target = make([]*UnionNullCustomerNotificationTypeCustomerNotificationDto, 0, s)
	}
}
func (r ArrayUnionNullCustomerNotificationTypeCustomerNotificationDtoWrapper) NullField(i int) {
	(*r.Target)[len(*r.Target)-1] = nil
}

func (r ArrayUnionNullCustomerNotificationTypeCustomerNotificationDtoWrapper) AppendArray() types.Field {
	var v *UnionNullCustomerNotificationTypeCustomerNotificationDto
	v = NewUnionNullCustomerNotificationTypeCustomerNotificationDto()

	*r.Target = append(*r.Target, v)

	return (*r.Target)[len(*r.Target)-1]
}
