// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     100493_1.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

type UnionNullOperationTypeEnum int

const (
	UnionNullOperationTypeEnumOperation UnionNullOperationTypeEnum = 1
)

type UnionNullOperation struct {
	Null      *types.NullVal
	Operation Operation
	UnionType UnionNullOperationTypeEnum
}

func writeUnionNullOperation(r *UnionNullOperation, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionNullOperationTypeEnumOperation:
		return writeOperation(r.Operation, w)
	}
	return fmt.Errorf("invalid value for *UnionNullOperation")
}

func NewUnionNullOperation() *UnionNullOperation {
	return &UnionNullOperation{}
}

func (r *UnionNullOperation) Serialize(w io.Writer) error {
	return writeUnionNullOperation(r, w)
}

func DeserializeUnionNullOperation(r io.Reader) (*UnionNullOperation, error) {
	t := NewUnionNullOperation()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func DeserializeUnionNullOperationFromSchema(r io.Reader, schema string) (*UnionNullOperation, error) {
	t := NewUnionNullOperation()
	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func (r *UnionNullOperation) Schema() string {
	return "[\"null\",{\"fields\":[{\"default\":null,\"name\":\"CorrelationId\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"MessageType\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"Type\",\"type\":[\"null\",\"string\"]}],\"name\":\"Operation\",\"type\":\"record\"}]"
}

func (_ *UnionNullOperation) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *UnionNullOperation) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *UnionNullOperation) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *UnionNullOperation) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullOperation) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *UnionNullOperation) SetString(v string)  { panic("Unsupported operation") }

func (r *UnionNullOperation) SetLong(v int64) {

	r.UnionType = (UnionNullOperationTypeEnum)(v)
}

func (r *UnionNullOperation) Get(i int) types.Field {

	switch i {
	case 0:
		return r.Null
	case 1:
		r.Operation = NewOperation()
		return &types.Record{Target: (&r.Operation)}
	}
	panic("Unknown field index")
}
func (_ *UnionNullOperation) NullField(i int)                  { panic("Unsupported operation") }
func (_ *UnionNullOperation) HintSize(i int)                   { panic("Unsupported operation") }
func (_ *UnionNullOperation) SetDefault(i int)                 { panic("Unsupported operation") }
func (_ *UnionNullOperation) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullOperation) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *UnionNullOperation) Finalize()                        {}

func (r *UnionNullOperation) MarshalJSON() ([]byte, error) {

	if r == nil {
		return []byte("null"), nil
	}

	switch r.UnionType {
	case UnionNullOperationTypeEnumOperation:
		return json.Marshal(map[string]interface{}{"SmokeTests.Kafka.Dto.TelemetryScada.Operation": r.Operation})
	}
	return nil, fmt.Errorf("invalid value for *UnionNullOperation")
}

func (r *UnionNullOperation) UnmarshalJSON(data []byte) error {

	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if len(fields) > 1 {
		return fmt.Errorf("more than one type supplied for union")
	}
	if value, ok := fields["SmokeTests.Kafka.Dto.TelemetryScada.Operation"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.Operation)
	}
	return fmt.Errorf("invalid value for *UnionNullOperation")
}
