// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     100480_13.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/container"
	"github.com/actgardner/gogen-avro/v10/vm"
)

func NewInnflyttReversertWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := NewInnflyttReversert()
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

// container reader
type InnflyttReversertReader struct {
	r io.Reader
	p *vm.Program
}

func NewInnflyttReversertReader(r io.Reader) (*InnflyttReversertReader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewInnflyttReversert()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &InnflyttReversertReader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r InnflyttReversertReader) Read() (InnflyttReversert, error) {
	t := NewInnflyttReversert()
	err := vm.Eval(r.r, r.p, &t)
	return t, err
}
