// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     100242_2.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

func writeArrayUnionNullEnergyPrice(r []*UnionNullEnergyPrice, w io.Writer) error {
	err := vm.WriteLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for _, e := range r {
		err = writeUnionNullEnergyPrice(e, w)
		if err != nil {
			return err
		}
	}
	return vm.WriteLong(0, w)
}

type ArrayUnionNullEnergyPriceWrapper struct {
	Target *[]*UnionNullEnergyPrice
}

func (_ ArrayUnionNullEnergyPriceWrapper) SetBoolean(v bool)     { panic("Unsupported operation") }
func (_ ArrayUnionNullEnergyPriceWrapper) SetInt(v int32)        { panic("Unsupported operation") }
func (_ ArrayUnionNullEnergyPriceWrapper) SetLong(v int64)       { panic("Unsupported operation") }
func (_ ArrayUnionNullEnergyPriceWrapper) SetFloat(v float32)    { panic("Unsupported operation") }
func (_ ArrayUnionNullEnergyPriceWrapper) SetDouble(v float64)   { panic("Unsupported operation") }
func (_ ArrayUnionNullEnergyPriceWrapper) SetBytes(v []byte)     { panic("Unsupported operation") }
func (_ ArrayUnionNullEnergyPriceWrapper) SetString(v string)    { panic("Unsupported operation") }
func (_ ArrayUnionNullEnergyPriceWrapper) SetUnionElem(v int64)  { panic("Unsupported operation") }
func (_ ArrayUnionNullEnergyPriceWrapper) Get(i int) types.Field { panic("Unsupported operation") }
func (_ ArrayUnionNullEnergyPriceWrapper) AppendMap(key string) types.Field {
	panic("Unsupported operation")
}
func (_ ArrayUnionNullEnergyPriceWrapper) Finalize()        {}
func (_ ArrayUnionNullEnergyPriceWrapper) SetDefault(i int) { panic("Unsupported operation") }
func (r ArrayUnionNullEnergyPriceWrapper) HintSize(s int) {
	if len(*r.Target) == 0 {
		*r.Target = make([]*UnionNullEnergyPrice, 0, s)
	}
}
func (r ArrayUnionNullEnergyPriceWrapper) NullField(i int) {
	(*r.Target)[len(*r.Target)-1] = nil
}

func (r ArrayUnionNullEnergyPriceWrapper) AppendArray() types.Field {
	var v *UnionNullEnergyPrice
	v = NewUnionNullEnergyPrice()

	*r.Target = append(*r.Target, v)

	return (*r.Target)[len(*r.Target)-1]
}
