// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     100242_2.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/container"
	"github.com/actgardner/gogen-avro/v10/vm"
)

func NewFixedPriceConfigurationWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := NewFixedPriceConfiguration()
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

// container reader
type FixedPriceConfigurationReader struct {
	r io.Reader
	p *vm.Program
}

func NewFixedPriceConfigurationReader(r io.Reader) (*FixedPriceConfigurationReader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewFixedPriceConfiguration()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &FixedPriceConfigurationReader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r FixedPriceConfigurationReader) Read() (FixedPriceConfiguration, error) {
	t := NewFixedPriceConfiguration()
	err := vm.Eval(r.r, r.p, &t)
	return t, err
}
