// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     100242_2.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

type UnionNullEnergyPrice2TypeEnum int

const (
	UnionNullEnergyPrice2TypeEnumEnergyPrice2 UnionNullEnergyPrice2TypeEnum = 1
)

type UnionNullEnergyPrice2 struct {
	Null         *types.NullVal
	EnergyPrice2 EnergyPrice2
	UnionType    UnionNullEnergyPrice2TypeEnum
}

func writeUnionNullEnergyPrice2(r *UnionNullEnergyPrice2, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionNullEnergyPrice2TypeEnumEnergyPrice2:
		return writeEnergyPrice2(r.EnergyPrice2, w)
	}
	return fmt.Errorf("invalid value for *UnionNullEnergyPrice2")
}

func NewUnionNullEnergyPrice2() *UnionNullEnergyPrice2 {
	return &UnionNullEnergyPrice2{}
}

func (r *UnionNullEnergyPrice2) Serialize(w io.Writer) error {
	return writeUnionNullEnergyPrice2(r, w)
}

func DeserializeUnionNullEnergyPrice2(r io.Reader) (*UnionNullEnergyPrice2, error) {
	t := NewUnionNullEnergyPrice2()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func DeserializeUnionNullEnergyPrice2FromSchema(r io.Reader, schema string) (*UnionNullEnergyPrice2, error) {
	t := NewUnionNullEnergyPrice2()
	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func (r *UnionNullEnergyPrice2) Schema() string {
	return "[\"null\",{\"fields\":[{\"default\":null,\"name\":\"Currency\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"EnergyPriceLevel\",\"type\":[\"null\",{\"items\":[\"null\",{\"fields\":[{\"default\":null,\"name\":\"EnergyExTaxes\",\"type\":[\"null\",\"double\"]},{\"default\":null,\"name\":\"Hours\",\"type\":[\"null\",{\"items\":\"int\",\"type\":\"array\"}]},{\"default\":null,\"name\":\"Id\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"Level\",\"type\":[\"null\",\"string\"]}],\"name\":\"EnergyPrice\",\"type\":\"record\"}],\"type\":\"array\"}]},{\"default\":null,\"name\":\"MonetaryUnitOfMeasure\",\"type\":[\"null\",\"string\"]}],\"name\":\"EnergyPrice2\",\"type\":\"record\"}]"
}

func (_ *UnionNullEnergyPrice2) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *UnionNullEnergyPrice2) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *UnionNullEnergyPrice2) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *UnionNullEnergyPrice2) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullEnergyPrice2) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *UnionNullEnergyPrice2) SetString(v string)  { panic("Unsupported operation") }

func (r *UnionNullEnergyPrice2) SetLong(v int64) {

	r.UnionType = (UnionNullEnergyPrice2TypeEnum)(v)
}

func (r *UnionNullEnergyPrice2) Get(i int) types.Field {

	switch i {
	case 0:
		return r.Null
	case 1:
		r.EnergyPrice2 = NewEnergyPrice2()
		return &types.Record{Target: (&r.EnergyPrice2)}
	}
	panic("Unknown field index")
}
func (_ *UnionNullEnergyPrice2) NullField(i int)                  { panic("Unsupported operation") }
func (_ *UnionNullEnergyPrice2) HintSize(i int)                   { panic("Unsupported operation") }
func (_ *UnionNullEnergyPrice2) SetDefault(i int)                 { panic("Unsupported operation") }
func (_ *UnionNullEnergyPrice2) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullEnergyPrice2) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *UnionNullEnergyPrice2) Finalize()                        {}

func (r *UnionNullEnergyPrice2) MarshalJSON() ([]byte, error) {

	if r == nil {
		return []byte("null"), nil
	}

	switch r.UnionType {
	case UnionNullEnergyPrice2TypeEnumEnergyPrice2:
		return json.Marshal(map[string]interface{}{"GridTariff.Events.V1.EnergyPrice2": r.EnergyPrice2})
	}
	return nil, fmt.Errorf("invalid value for *UnionNullEnergyPrice2")
}

func (r *UnionNullEnergyPrice2) UnmarshalJSON(data []byte) error {

	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if len(fields) > 1 {
		return fmt.Errorf("more than one type supplied for union")
	}
	if value, ok := fields["GridTariff.Events.V1.EnergyPrice2"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.EnergyPrice2)
	}
	return fmt.Errorf("invalid value for *UnionNullEnergyPrice2")
}
