// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     100242_2.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

type UnionNullFixedPricesTypeEnum int

const (
	UnionNullFixedPricesTypeEnumFixedPrices UnionNullFixedPricesTypeEnum = 1
)

type UnionNullFixedPrices struct {
	Null        *types.NullVal
	FixedPrices FixedPrices
	UnionType   UnionNullFixedPricesTypeEnum
}

func writeUnionNullFixedPrices(r *UnionNullFixedPrices, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionNullFixedPricesTypeEnumFixedPrices:
		return writeFixedPrices(r.FixedPrices, w)
	}
	return fmt.Errorf("invalid value for *UnionNullFixedPrices")
}

func NewUnionNullFixedPrices() *UnionNullFixedPrices {
	return &UnionNullFixedPrices{}
}

func (r *UnionNullFixedPrices) Serialize(w io.Writer) error {
	return writeUnionNullFixedPrices(r, w)
}

func DeserializeUnionNullFixedPrices(r io.Reader) (*UnionNullFixedPrices, error) {
	t := NewUnionNullFixedPrices()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func DeserializeUnionNullFixedPricesFromSchema(r io.Reader, schema string) (*UnionNullFixedPrices, error) {
	t := NewUnionNullFixedPrices()
	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func (r *UnionNullFixedPrices) Schema() string {
	return "[\"null\",{\"fields\":[{\"default\":null,\"name\":\"FixedPriceLevel\",\"type\":[\"null\",{\"items\":[\"null\",{\"fields\":[{\"default\":null,\"name\":\"Currency\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"Id\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"LevelInfo\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"MonetaryUnitOfMeasure\",\"type\":[\"null\",\"string\"]},{\"name\":\"MonthlyFixedExTaxes\",\"type\":\"double\"},{\"default\":null,\"name\":\"MonthlyUnitOfMeasure\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"NextIdDown\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"NextIdUp\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"ValueMax\",\"type\":[\"null\",\"double\"]},{\"default\":null,\"name\":\"ValueMin\",\"type\":[\"null\",\"double\"]},{\"default\":null,\"name\":\"ValueUnitOfMeasure\",\"type\":[\"null\",\"string\"]}],\"name\":\"FixedPriceLevel\",\"type\":\"record\"}],\"type\":\"array\"}]},{\"default\":null,\"name\":\"Id\",\"type\":[\"null\",\"string\"]}],\"name\":\"FixedPrices\",\"type\":\"record\"}]"
}

func (_ *UnionNullFixedPrices) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *UnionNullFixedPrices) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *UnionNullFixedPrices) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *UnionNullFixedPrices) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullFixedPrices) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *UnionNullFixedPrices) SetString(v string)  { panic("Unsupported operation") }

func (r *UnionNullFixedPrices) SetLong(v int64) {

	r.UnionType = (UnionNullFixedPricesTypeEnum)(v)
}

func (r *UnionNullFixedPrices) Get(i int) types.Field {

	switch i {
	case 0:
		return r.Null
	case 1:
		r.FixedPrices = NewFixedPrices()
		return &types.Record{Target: (&r.FixedPrices)}
	}
	panic("Unknown field index")
}
func (_ *UnionNullFixedPrices) NullField(i int)                  { panic("Unsupported operation") }
func (_ *UnionNullFixedPrices) HintSize(i int)                   { panic("Unsupported operation") }
func (_ *UnionNullFixedPrices) SetDefault(i int)                 { panic("Unsupported operation") }
func (_ *UnionNullFixedPrices) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullFixedPrices) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *UnionNullFixedPrices) Finalize()                        {}

func (r *UnionNullFixedPrices) MarshalJSON() ([]byte, error) {

	if r == nil {
		return []byte("null"), nil
	}

	switch r.UnionType {
	case UnionNullFixedPricesTypeEnumFixedPrices:
		return json.Marshal(map[string]interface{}{"GridTariff.Events.V1.FixedPrices": r.FixedPrices})
	}
	return nil, fmt.Errorf("invalid value for *UnionNullFixedPrices")
}

func (r *UnionNullFixedPrices) UnmarshalJSON(data []byte) error {

	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if len(fields) > 1 {
		return fmt.Errorf("more than one type supplied for union")
	}
	if value, ok := fields["GridTariff.Events.V1.FixedPrices"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.FixedPrices)
	}
	return fmt.Errorf("invalid value for *UnionNullFixedPrices")
}
