// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     100242_2.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

type UnionNullFixedPriceLevelTypeEnum int

const (
	UnionNullFixedPriceLevelTypeEnumFixedPriceLevel UnionNullFixedPriceLevelTypeEnum = 1
)

type UnionNullFixedPriceLevel struct {
	Null            *types.NullVal
	FixedPriceLevel FixedPriceLevel
	UnionType       UnionNullFixedPriceLevelTypeEnum
}

func writeUnionNullFixedPriceLevel(r *UnionNullFixedPriceLevel, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionNullFixedPriceLevelTypeEnumFixedPriceLevel:
		return writeFixedPriceLevel(r.FixedPriceLevel, w)
	}
	return fmt.Errorf("invalid value for *UnionNullFixedPriceLevel")
}

func NewUnionNullFixedPriceLevel() *UnionNullFixedPriceLevel {
	return &UnionNullFixedPriceLevel{}
}

func (r *UnionNullFixedPriceLevel) Serialize(w io.Writer) error {
	return writeUnionNullFixedPriceLevel(r, w)
}

func DeserializeUnionNullFixedPriceLevel(r io.Reader) (*UnionNullFixedPriceLevel, error) {
	t := NewUnionNullFixedPriceLevel()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func DeserializeUnionNullFixedPriceLevelFromSchema(r io.Reader, schema string) (*UnionNullFixedPriceLevel, error) {
	t := NewUnionNullFixedPriceLevel()
	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func (r *UnionNullFixedPriceLevel) Schema() string {
	return "[\"null\",{\"fields\":[{\"default\":null,\"name\":\"Currency\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"Id\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"LevelInfo\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"MonetaryUnitOfMeasure\",\"type\":[\"null\",\"string\"]},{\"name\":\"MonthlyFixedExTaxes\",\"type\":\"double\"},{\"default\":null,\"name\":\"MonthlyUnitOfMeasure\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"NextIdDown\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"NextIdUp\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"ValueMax\",\"type\":[\"null\",\"double\"]},{\"default\":null,\"name\":\"ValueMin\",\"type\":[\"null\",\"double\"]},{\"default\":null,\"name\":\"ValueUnitOfMeasure\",\"type\":[\"null\",\"string\"]}],\"name\":\"FixedPriceLevel\",\"type\":\"record\"}]"
}

func (_ *UnionNullFixedPriceLevel) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *UnionNullFixedPriceLevel) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *UnionNullFixedPriceLevel) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *UnionNullFixedPriceLevel) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullFixedPriceLevel) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *UnionNullFixedPriceLevel) SetString(v string)  { panic("Unsupported operation") }

func (r *UnionNullFixedPriceLevel) SetLong(v int64) {

	r.UnionType = (UnionNullFixedPriceLevelTypeEnum)(v)
}

func (r *UnionNullFixedPriceLevel) Get(i int) types.Field {

	switch i {
	case 0:
		return r.Null
	case 1:
		r.FixedPriceLevel = NewFixedPriceLevel()
		return &types.Record{Target: (&r.FixedPriceLevel)}
	}
	panic("Unknown field index")
}
func (_ *UnionNullFixedPriceLevel) NullField(i int)                  { panic("Unsupported operation") }
func (_ *UnionNullFixedPriceLevel) HintSize(i int)                   { panic("Unsupported operation") }
func (_ *UnionNullFixedPriceLevel) SetDefault(i int)                 { panic("Unsupported operation") }
func (_ *UnionNullFixedPriceLevel) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullFixedPriceLevel) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *UnionNullFixedPriceLevel) Finalize()                        {}

func (r *UnionNullFixedPriceLevel) MarshalJSON() ([]byte, error) {

	if r == nil {
		return []byte("null"), nil
	}

	switch r.UnionType {
	case UnionNullFixedPriceLevelTypeEnumFixedPriceLevel:
		return json.Marshal(map[string]interface{}{"GridTariff.Events.V1.FixedPriceLevel": r.FixedPriceLevel})
	}
	return nil, fmt.Errorf("invalid value for *UnionNullFixedPriceLevel")
}

func (r *UnionNullFixedPriceLevel) UnmarshalJSON(data []byte) error {

	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if len(fields) > 1 {
		return fmt.Errorf("more than one type supplied for union")
	}
	if value, ok := fields["GridTariff.Events.V1.FixedPriceLevel"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.FixedPriceLevel)
	}
	return fmt.Errorf("invalid value for *UnionNullFixedPriceLevel")
}
