// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     100242_2.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

type UnionNullPowerPriceTypeEnum int

const (
	UnionNullPowerPriceTypeEnumPowerPrice UnionNullPowerPriceTypeEnum = 1
)

type UnionNullPowerPrice struct {
	Null       *types.NullVal
	PowerPrice PowerPrice
	UnionType  UnionNullPowerPriceTypeEnum
}

func writeUnionNullPowerPrice(r *UnionNullPowerPrice, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionNullPowerPriceTypeEnumPowerPrice:
		return writePowerPrice(r.PowerPrice, w)
	}
	return fmt.Errorf("invalid value for *UnionNullPowerPrice")
}

func NewUnionNullPowerPrice() *UnionNullPowerPrice {
	return &UnionNullPowerPrice{}
}

func (r *UnionNullPowerPrice) Serialize(w io.Writer) error {
	return writeUnionNullPowerPrice(r, w)
}

func DeserializeUnionNullPowerPrice(r io.Reader) (*UnionNullPowerPrice, error) {
	t := NewUnionNullPowerPrice()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func DeserializeUnionNullPowerPriceFromSchema(r io.Reader, schema string) (*UnionNullPowerPrice, error) {
	t := NewUnionNullPowerPrice()
	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func (r *UnionNullPowerPrice) Schema() string {
	return "[\"null\",{\"fields\":[{\"default\":null,\"name\":\"Currency\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"Id\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"LevelInfo\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"MonetaryUnitOfMeasure\",\"type\":[\"null\",\"string\"]},{\"name\":\"MonthlyActivePowerExTaxes\",\"type\":\"double\"},{\"default\":null,\"name\":\"MonthlyReactivePowerExTaxes\",\"type\":[\"null\",\"double\"]},{\"default\":null,\"name\":\"MonthlyUnitOfMeasure\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"NextIdDown\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"NextIdUp\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"ValueMax\",\"type\":[\"null\",\"double\"]},{\"default\":null,\"name\":\"ValueMin\",\"type\":[\"null\",\"double\"]},{\"default\":null,\"name\":\"ValueUnitOfMeasure\",\"type\":[\"null\",\"string\"]}],\"name\":\"PowerPrice\",\"type\":\"record\"}]"
}

func (_ *UnionNullPowerPrice) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *UnionNullPowerPrice) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *UnionNullPowerPrice) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *UnionNullPowerPrice) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullPowerPrice) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *UnionNullPowerPrice) SetString(v string)  { panic("Unsupported operation") }

func (r *UnionNullPowerPrice) SetLong(v int64) {

	r.UnionType = (UnionNullPowerPriceTypeEnum)(v)
}

func (r *UnionNullPowerPrice) Get(i int) types.Field {

	switch i {
	case 0:
		return r.Null
	case 1:
		r.PowerPrice = NewPowerPrice()
		return &types.Record{Target: (&r.PowerPrice)}
	}
	panic("Unknown field index")
}
func (_ *UnionNullPowerPrice) NullField(i int)                  { panic("Unsupported operation") }
func (_ *UnionNullPowerPrice) HintSize(i int)                   { panic("Unsupported operation") }
func (_ *UnionNullPowerPrice) SetDefault(i int)                 { panic("Unsupported operation") }
func (_ *UnionNullPowerPrice) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullPowerPrice) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *UnionNullPowerPrice) Finalize()                        {}

func (r *UnionNullPowerPrice) MarshalJSON() ([]byte, error) {

	if r == nil {
		return []byte("null"), nil
	}

	switch r.UnionType {
	case UnionNullPowerPriceTypeEnumPowerPrice:
		return json.Marshal(map[string]interface{}{"GridTariff.Events.V1.PowerPrice": r.PowerPrice})
	}
	return nil, fmt.Errorf("invalid value for *UnionNullPowerPrice")
}

func (r *UnionNullPowerPrice) UnmarshalJSON(data []byte) error {

	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if len(fields) > 1 {
		return fmt.Errorf("more than one type supplied for union")
	}
	if value, ok := fields["GridTariff.Events.V1.PowerPrice"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.PowerPrice)
	}
	return fmt.Errorf("invalid value for *UnionNullPowerPrice")
}
