// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     100189_1.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/container"
	"github.com/actgardner/gogen-avro/v10/vm"
)

func NewMessageWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := NewMessage()
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

// container reader
type MessageReader struct {
	r io.Reader
	p *vm.Program
}

func NewMessageReader(r io.Reader) (*MessageReader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewMessage()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &MessageReader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r MessageReader) Read() (Message, error) {
	t := NewMessage()
	err := vm.Eval(r.r, r.p, &t)
	return t, err
}
