// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     100159_3.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

type UnionNullNetProductTypeEnum int

const (
	UnionNullNetProductTypeEnumNetProduct UnionNullNetProductTypeEnum = 1
)

type UnionNullNetProduct struct {
	Null       *types.NullVal
	NetProduct NetProduct
	UnionType  UnionNullNetProductTypeEnum
}

func writeUnionNullNetProduct(r *UnionNullNetProduct, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionNullNetProductTypeEnumNetProduct:
		return writeNetProduct(r.NetProduct, w)
	}
	return fmt.Errorf("invalid value for *UnionNullNetProduct")
}

func NewUnionNullNetProduct() *UnionNullNetProduct {
	return &UnionNullNetProduct{}
}

func (r *UnionNullNetProduct) Serialize(w io.Writer) error {
	return writeUnionNullNetProduct(r, w)
}

func DeserializeUnionNullNetProduct(r io.Reader) (*UnionNullNetProduct, error) {
	t := NewUnionNullNetProduct()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func DeserializeUnionNullNetProductFromSchema(r io.Reader, schema string) (*UnionNullNetProduct, error) {
	t := NewUnionNullNetProduct()
	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func (r *UnionNullNetProduct) Schema() string {
	return "[\"null\",{\"fields\":[{\"default\":null,\"name\":\"Description\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"Name\",\"type\":[\"null\",\"string\"]},{\"name\":\"NetProductId\",\"type\":\"int\"}],\"name\":\"NetProduct\",\"type\":\"record\"}]"
}

func (_ *UnionNullNetProduct) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *UnionNullNetProduct) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *UnionNullNetProduct) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *UnionNullNetProduct) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullNetProduct) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *UnionNullNetProduct) SetString(v string)  { panic("Unsupported operation") }

func (r *UnionNullNetProduct) SetLong(v int64) {

	r.UnionType = (UnionNullNetProductTypeEnum)(v)
}

func (r *UnionNullNetProduct) Get(i int) types.Field {

	switch i {
	case 0:
		return r.Null
	case 1:
		r.NetProduct = NewNetProduct()
		return &types.Record{Target: (&r.NetProduct)}
	}
	panic("Unknown field index")
}
func (_ *UnionNullNetProduct) NullField(i int)                  { panic("Unsupported operation") }
func (_ *UnionNullNetProduct) HintSize(i int)                   { panic("Unsupported operation") }
func (_ *UnionNullNetProduct) SetDefault(i int)                 { panic("Unsupported operation") }
func (_ *UnionNullNetProduct) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullNetProduct) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *UnionNullNetProduct) Finalize()                        {}

func (r *UnionNullNetProduct) MarshalJSON() ([]byte, error) {

	if r == nil {
		return []byte("null"), nil
	}

	switch r.UnionType {
	case UnionNullNetProductTypeEnumNetProduct:
		return json.Marshal(map[string]interface{}{"Skogshorn.Kunde.Schemas.Entities.NetProduct": r.NetProduct})
	}
	return nil, fmt.Errorf("invalid value for *UnionNullNetProduct")
}

func (r *UnionNullNetProduct) UnmarshalJSON(data []byte) error {

	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if len(fields) > 1 {
		return fmt.Errorf("more than one type supplied for union")
	}
	if value, ok := fields["Skogshorn.Kunde.Schemas.Entities.NetProduct"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.NetProduct)
	}
	return fmt.Errorf("invalid value for *UnionNullNetProduct")
}
