// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     100058_21.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

type UnionNullCustomerTypeTypeEnum int

const (
	UnionNullCustomerTypeTypeEnumCustomerType UnionNullCustomerTypeTypeEnum = 1
)

type UnionNullCustomerType struct {
	Null         *types.NullVal
	CustomerType CustomerType
	UnionType    UnionNullCustomerTypeTypeEnum
}

func writeUnionNullCustomerType(r *UnionNullCustomerType, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionNullCustomerTypeTypeEnumCustomerType:
		return writeCustomerType(r.CustomerType, w)
	}
	return fmt.Errorf("invalid value for *UnionNullCustomerType")
}

func NewUnionNullCustomerType() *UnionNullCustomerType {
	return &UnionNullCustomerType{}
}

func (r *UnionNullCustomerType) Serialize(w io.Writer) error {
	return writeUnionNullCustomerType(r, w)
}

func DeserializeUnionNullCustomerType(r io.Reader) (*UnionNullCustomerType, error) {
	t := NewUnionNullCustomerType()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func DeserializeUnionNullCustomerTypeFromSchema(r io.Reader, schema string) (*UnionNullCustomerType, error) {
	t := NewUnionNullCustomerType()
	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func (r *UnionNullCustomerType) Schema() string {
	return "[\"null\",{\"name\":\"CustomerType\",\"symbols\":[\"Household\",\"Industry\"],\"type\":\"enum\"}]"
}

func (_ *UnionNullCustomerType) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *UnionNullCustomerType) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *UnionNullCustomerType) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *UnionNullCustomerType) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullCustomerType) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *UnionNullCustomerType) SetString(v string)  { panic("Unsupported operation") }

func (r *UnionNullCustomerType) SetLong(v int64) {

	r.UnionType = (UnionNullCustomerTypeTypeEnum)(v)
}

func (r *UnionNullCustomerType) Get(i int) types.Field {

	switch i {
	case 0:
		return r.Null
	case 1:
		return &CustomerTypeWrapper{Target: (&r.CustomerType)}
	}
	panic("Unknown field index")
}
func (_ *UnionNullCustomerType) NullField(i int)                  { panic("Unsupported operation") }
func (_ *UnionNullCustomerType) HintSize(i int)                   { panic("Unsupported operation") }
func (_ *UnionNullCustomerType) SetDefault(i int)                 { panic("Unsupported operation") }
func (_ *UnionNullCustomerType) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullCustomerType) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *UnionNullCustomerType) Finalize()                        {}

func (r *UnionNullCustomerType) MarshalJSON() ([]byte, error) {

	if r == nil {
		return []byte("null"), nil
	}

	switch r.UnionType {
	case UnionNullCustomerTypeTypeEnumCustomerType:
		return json.Marshal(map[string]interface{}{"Msim.Domain.Model.MeteringPoints.CustomerType": r.CustomerType})
	}
	return nil, fmt.Errorf("invalid value for *UnionNullCustomerType")
}

func (r *UnionNullCustomerType) UnmarshalJSON(data []byte) error {

	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if len(fields) > 1 {
		return fmt.Errorf("more than one type supplied for union")
	}
	if value, ok := fields["Msim.Domain.Model.MeteringPoints.CustomerType"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.CustomerType)
	}
	return fmt.Errorf("invalid value for *UnionNullCustomerType")
}
