// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     100058_21.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

type UnionNullCommunicationModuleTypeEnum int

const (
	UnionNullCommunicationModuleTypeEnumCommunicationModule UnionNullCommunicationModuleTypeEnum = 1
)

type UnionNullCommunicationModule struct {
	Null                *types.NullVal
	CommunicationModule CommunicationModule
	UnionType           UnionNullCommunicationModuleTypeEnum
}

func writeUnionNullCommunicationModule(r *UnionNullCommunicationModule, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionNullCommunicationModuleTypeEnumCommunicationModule:
		return writeCommunicationModule(r.CommunicationModule, w)
	}
	return fmt.Errorf("invalid value for *UnionNullCommunicationModule")
}

func NewUnionNullCommunicationModule() *UnionNullCommunicationModule {
	return &UnionNullCommunicationModule{}
}

func (r *UnionNullCommunicationModule) Serialize(w io.Writer) error {
	return writeUnionNullCommunicationModule(r, w)
}

func DeserializeUnionNullCommunicationModule(r io.Reader) (*UnionNullCommunicationModule, error) {
	t := NewUnionNullCommunicationModule()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func DeserializeUnionNullCommunicationModuleFromSchema(r io.Reader, schema string) (*UnionNullCommunicationModule, error) {
	t := NewUnionNullCommunicationModule()
	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func (r *UnionNullCommunicationModule) Schema() string {
	return "[\"null\",{\"fields\":[{\"default\":null,\"name\":\"FirmwareVersion\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"HesInstance\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"ModelId\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"OwnerId\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"ProductionYear\",\"type\":[\"null\",\"int\"]},{\"default\":null,\"name\":\"SerialNumber\",\"type\":[\"null\",\"string\"]}],\"name\":\"CommunicationModule\",\"type\":\"record\"}]"
}

func (_ *UnionNullCommunicationModule) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *UnionNullCommunicationModule) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *UnionNullCommunicationModule) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *UnionNullCommunicationModule) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullCommunicationModule) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *UnionNullCommunicationModule) SetString(v string)  { panic("Unsupported operation") }

func (r *UnionNullCommunicationModule) SetLong(v int64) {

	r.UnionType = (UnionNullCommunicationModuleTypeEnum)(v)
}

func (r *UnionNullCommunicationModule) Get(i int) types.Field {

	switch i {
	case 0:
		return r.Null
	case 1:
		r.CommunicationModule = NewCommunicationModule()
		return &types.Record{Target: (&r.CommunicationModule)}
	}
	panic("Unknown field index")
}
func (_ *UnionNullCommunicationModule) NullField(i int)  { panic("Unsupported operation") }
func (_ *UnionNullCommunicationModule) HintSize(i int)   { panic("Unsupported operation") }
func (_ *UnionNullCommunicationModule) SetDefault(i int) { panic("Unsupported operation") }
func (_ *UnionNullCommunicationModule) AppendMap(key string) types.Field {
	panic("Unsupported operation")
}
func (_ *UnionNullCommunicationModule) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *UnionNullCommunicationModule) Finalize()                {}

func (r *UnionNullCommunicationModule) MarshalJSON() ([]byte, error) {

	if r == nil {
		return []byte("null"), nil
	}

	switch r.UnionType {
	case UnionNullCommunicationModuleTypeEnumCommunicationModule:
		return json.Marshal(map[string]interface{}{"Msim.Domain.Model.Meters.CommunicationModule": r.CommunicationModule})
	}
	return nil, fmt.Errorf("invalid value for *UnionNullCommunicationModule")
}

func (r *UnionNullCommunicationModule) UnmarshalJSON(data []byte) error {

	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if len(fields) > 1 {
		return fmt.Errorf("more than one type supplied for union")
	}
	if value, ok := fields["Msim.Domain.Model.Meters.CommunicationModule"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.CommunicationModule)
	}
	return fmt.Errorf("invalid value for *UnionNullCommunicationModule")
}
