// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     100058_21.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

type UnionNullDeviceEnvironmentTypeEnum int

const (
	UnionNullDeviceEnvironmentTypeEnumDeviceEnvironment UnionNullDeviceEnvironmentTypeEnum = 1
)

type UnionNullDeviceEnvironment struct {
	Null              *types.NullVal
	DeviceEnvironment DeviceEnvironment
	UnionType         UnionNullDeviceEnvironmentTypeEnum
}

func writeUnionNullDeviceEnvironment(r *UnionNullDeviceEnvironment, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionNullDeviceEnvironmentTypeEnumDeviceEnvironment:
		return writeDeviceEnvironment(r.DeviceEnvironment, w)
	}
	return fmt.Errorf("invalid value for *UnionNullDeviceEnvironment")
}

func NewUnionNullDeviceEnvironment() *UnionNullDeviceEnvironment {
	return &UnionNullDeviceEnvironment{}
}

func (r *UnionNullDeviceEnvironment) Serialize(w io.Writer) error {
	return writeUnionNullDeviceEnvironment(r, w)
}

func DeserializeUnionNullDeviceEnvironment(r io.Reader) (*UnionNullDeviceEnvironment, error) {
	t := NewUnionNullDeviceEnvironment()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func DeserializeUnionNullDeviceEnvironmentFromSchema(r io.Reader, schema string) (*UnionNullDeviceEnvironment, error) {
	t := NewUnionNullDeviceEnvironment()
	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func (r *UnionNullDeviceEnvironment) Schema() string {
	return "[\"null\",{\"name\":\"DeviceEnvironment\",\"namespace\":\"Msim.Domain.Model.Primitives\",\"symbols\":[\"Unknown\",\"T03\",\"T05\",\"StagingSouth\",\"ProductionSouth\",\"TestNorth\",\"StagingNorth\",\"ProductionNorth\"],\"type\":\"enum\"}]"
}

func (_ *UnionNullDeviceEnvironment) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *UnionNullDeviceEnvironment) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *UnionNullDeviceEnvironment) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *UnionNullDeviceEnvironment) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullDeviceEnvironment) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *UnionNullDeviceEnvironment) SetString(v string)  { panic("Unsupported operation") }

func (r *UnionNullDeviceEnvironment) SetLong(v int64) {

	r.UnionType = (UnionNullDeviceEnvironmentTypeEnum)(v)
}

func (r *UnionNullDeviceEnvironment) Get(i int) types.Field {

	switch i {
	case 0:
		return r.Null
	case 1:
		return &DeviceEnvironmentWrapper{Target: (&r.DeviceEnvironment)}
	}
	panic("Unknown field index")
}
func (_ *UnionNullDeviceEnvironment) NullField(i int)  { panic("Unsupported operation") }
func (_ *UnionNullDeviceEnvironment) HintSize(i int)   { panic("Unsupported operation") }
func (_ *UnionNullDeviceEnvironment) SetDefault(i int) { panic("Unsupported operation") }
func (_ *UnionNullDeviceEnvironment) AppendMap(key string) types.Field {
	panic("Unsupported operation")
}
func (_ *UnionNullDeviceEnvironment) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *UnionNullDeviceEnvironment) Finalize()                {}

func (r *UnionNullDeviceEnvironment) MarshalJSON() ([]byte, error) {

	if r == nil {
		return []byte("null"), nil
	}

	switch r.UnionType {
	case UnionNullDeviceEnvironmentTypeEnumDeviceEnvironment:
		return json.Marshal(map[string]interface{}{"Msim.Domain.Model.Primitives.DeviceEnvironment": r.DeviceEnvironment})
	}
	return nil, fmt.Errorf("invalid value for *UnionNullDeviceEnvironment")
}

func (r *UnionNullDeviceEnvironment) UnmarshalJSON(data []byte) error {

	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if len(fields) > 1 {
		return fmt.Errorf("more than one type supplied for union")
	}
	if value, ok := fields["Msim.Domain.Model.Primitives.DeviceEnvironment"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.DeviceEnvironment)
	}
	return fmt.Errorf("invalid value for *UnionNullDeviceEnvironment")
}
