// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     100062_2.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

func writeArrayUnionNullKsqlDataSourceSchema_CARS(r []*UnionNullKsqlDataSourceSchema_CARS, w io.Writer) error {
	err := vm.WriteLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for _, e := range r {
		err = writeUnionNullKsqlDataSourceSchema_CARS(e, w)
		if err != nil {
			return err
		}
	}
	return vm.WriteLong(0, w)
}

type ArrayUnionNullKsqlDataSourceSchema_CARSWrapper struct {
	Target *[]*UnionNullKsqlDataSourceSchema_CARS
}

func (_ ArrayUnionNullKsqlDataSourceSchema_CARSWrapper) SetBoolean(v bool) {
	panic("Unsupported operation")
}
func (_ ArrayUnionNullKsqlDataSourceSchema_CARSWrapper) SetInt(v int32) {
	panic("Unsupported operation")
}
func (_ ArrayUnionNullKsqlDataSourceSchema_CARSWrapper) SetLong(v int64) {
	panic("Unsupported operation")
}
func (_ ArrayUnionNullKsqlDataSourceSchema_CARSWrapper) SetFloat(v float32) {
	panic("Unsupported operation")
}
func (_ ArrayUnionNullKsqlDataSourceSchema_CARSWrapper) SetDouble(v float64) {
	panic("Unsupported operation")
}
func (_ ArrayUnionNullKsqlDataSourceSchema_CARSWrapper) SetBytes(v []byte) {
	panic("Unsupported operation")
}
func (_ ArrayUnionNullKsqlDataSourceSchema_CARSWrapper) SetString(v string) {
	panic("Unsupported operation")
}
func (_ ArrayUnionNullKsqlDataSourceSchema_CARSWrapper) SetUnionElem(v int64) {
	panic("Unsupported operation")
}
func (_ ArrayUnionNullKsqlDataSourceSchema_CARSWrapper) Get(i int) types.Field {
	panic("Unsupported operation")
}
func (_ ArrayUnionNullKsqlDataSourceSchema_CARSWrapper) AppendMap(key string) types.Field {
	panic("Unsupported operation")
}
func (_ ArrayUnionNullKsqlDataSourceSchema_CARSWrapper) Finalize() {}
func (_ ArrayUnionNullKsqlDataSourceSchema_CARSWrapper) SetDefault(i int) {
	panic("Unsupported operation")
}
func (r ArrayUnionNullKsqlDataSourceSchema_CARSWrapper) HintSize(s int) {
	if len(*r.Target) == 0 {
		*r.Target = make([]*UnionNullKsqlDataSourceSchema_CARS, 0, s)
	}
}
func (r ArrayUnionNullKsqlDataSourceSchema_CARSWrapper) NullField(i int) {
	(*r.Target)[len(*r.Target)-1] = nil
}

func (r ArrayUnionNullKsqlDataSourceSchema_CARSWrapper) AppendArray() types.Field {
	var v *UnionNullKsqlDataSourceSchema_CARS
	v = NewUnionNullKsqlDataSourceSchema_CARS()

	*r.Target = append(*r.Target, v)

	return (*r.Target)[len(*r.Target)-1]
}
