// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     100486_7.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

func writeArrayUnionNullSwitchPhaseDto(r []*UnionNullSwitchPhaseDto, w io.Writer) error {
	err := vm.WriteLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for _, e := range r {
		err = writeUnionNullSwitchPhaseDto(e, w)
		if err != nil {
			return err
		}
	}
	return vm.WriteLong(0, w)
}

type ArrayUnionNullSwitchPhaseDtoWrapper struct {
	Target *[]*UnionNullSwitchPhaseDto
}

func (_ ArrayUnionNullSwitchPhaseDtoWrapper) SetBoolean(v bool)     { panic("Unsupported operation") }
func (_ ArrayUnionNullSwitchPhaseDtoWrapper) SetInt(v int32)        { panic("Unsupported operation") }
func (_ ArrayUnionNullSwitchPhaseDtoWrapper) SetLong(v int64)       { panic("Unsupported operation") }
func (_ ArrayUnionNullSwitchPhaseDtoWrapper) SetFloat(v float32)    { panic("Unsupported operation") }
func (_ ArrayUnionNullSwitchPhaseDtoWrapper) SetDouble(v float64)   { panic("Unsupported operation") }
func (_ ArrayUnionNullSwitchPhaseDtoWrapper) SetBytes(v []byte)     { panic("Unsupported operation") }
func (_ ArrayUnionNullSwitchPhaseDtoWrapper) SetString(v string)    { panic("Unsupported operation") }
func (_ ArrayUnionNullSwitchPhaseDtoWrapper) SetUnionElem(v int64)  { panic("Unsupported operation") }
func (_ ArrayUnionNullSwitchPhaseDtoWrapper) Get(i int) types.Field { panic("Unsupported operation") }
func (_ ArrayUnionNullSwitchPhaseDtoWrapper) AppendMap(key string) types.Field {
	panic("Unsupported operation")
}
func (_ ArrayUnionNullSwitchPhaseDtoWrapper) Finalize()        {}
func (_ ArrayUnionNullSwitchPhaseDtoWrapper) SetDefault(i int) { panic("Unsupported operation") }
func (r ArrayUnionNullSwitchPhaseDtoWrapper) HintSize(s int) {
	if len(*r.Target) == 0 {
		*r.Target = make([]*UnionNullSwitchPhaseDto, 0, s)
	}
}
func (r ArrayUnionNullSwitchPhaseDtoWrapper) NullField(i int) {
	(*r.Target)[len(*r.Target)-1] = nil
}

func (r ArrayUnionNullSwitchPhaseDtoWrapper) AppendArray() types.Field {
	var v *UnionNullSwitchPhaseDto
	v = NewUnionNullSwitchPhaseDto()

	*r.Target = append(*r.Target, v)

	return (*r.Target)[len(*r.Target)-1]
}
