// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     100486_7.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type AssetSDto struct {
	MRID *UnionNullString `json:"MRID"`
}

const AssetSDtoAvroCRC64Fingerprint = "\xe4\xc6\x11\xbe\x86\xe4t\x8f"

func NewAssetSDto() AssetSDto {
	r := AssetSDto{}
	r.MRID = nil
	return r
}

func DeserializeAssetSDto(r io.Reader) (AssetSDto, error) {
	t := NewAssetSDto()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeAssetSDtoFromSchema(r io.Reader, schema string) (AssetSDto, error) {
	t := NewAssetSDto()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeAssetSDto(r AssetSDto, w io.Writer) error {
	var err error
	err = writeUnionNullString(r.MRID, w)
	if err != nil {
		return err
	}
	return err
}

func (r AssetSDto) Serialize(w io.Writer) error {
	return writeAssetSDto(r, w)
}

func (r AssetSDto) Schema() string {
	return "{\"fields\":[{\"default\":null,\"name\":\"MRID\",\"type\":[\"null\",\"string\"]}],\"name\":\"SesamResponseServices.SesamDomainObjects.AssetSDto\",\"type\":\"record\"}"
}

func (r AssetSDto) SchemaName() string {
	return "SesamResponseServices.SesamDomainObjects.AssetSDto"
}

func (_ AssetSDto) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ AssetSDto) SetInt(v int32)       { panic("Unsupported operation") }
func (_ AssetSDto) SetLong(v int64)      { panic("Unsupported operation") }
func (_ AssetSDto) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ AssetSDto) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ AssetSDto) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ AssetSDto) SetString(v string)   { panic("Unsupported operation") }
func (_ AssetSDto) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *AssetSDto) Get(i int) types.Field {
	switch i {
	case 0:
		r.MRID = NewUnionNullString()

		return r.MRID
	}
	panic("Unknown field index")
}

func (r *AssetSDto) SetDefault(i int) {
	switch i {
	case 0:
		r.MRID = nil
		return
	}
	panic("Unknown field index")
}

func (r *AssetSDto) NullField(i int) {
	switch i {
	case 0:
		r.MRID = nil
		return
	}
	panic("Not a nullable field index")
}

func (_ AssetSDto) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ AssetSDto) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ AssetSDto) HintSize(int)                     { panic("Unsupported operation") }
func (_ AssetSDto) Finalize()                        {}

func (_ AssetSDto) AvroCRC64Fingerprint() []byte {
	return []byte(AssetSDtoAvroCRC64Fingerprint)
}

func (r AssetSDto) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["MRID"], err = json.Marshal(r.MRID)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *AssetSDto) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["MRID"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.MRID); err != nil {
			return err
		}
	} else {
		r.MRID = NewUnionNullString()

		r.MRID = nil
	}
	return nil
}
