// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     100486_7.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type OperatorDto struct {
	Person *UnionNullPersonDto `json:"Person"`
}

const OperatorDtoAvroCRC64Fingerprint = "\x05\xc3\fyGt\x01a"

func NewOperatorDto() OperatorDto {
	r := OperatorDto{}
	r.Person = nil
	return r
}

func DeserializeOperatorDto(r io.Reader) (OperatorDto, error) {
	t := NewOperatorDto()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeOperatorDtoFromSchema(r io.Reader, schema string) (OperatorDto, error) {
	t := NewOperatorDto()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeOperatorDto(r OperatorDto, w io.Writer) error {
	var err error
	err = writeUnionNullPersonDto(r.Person, w)
	if err != nil {
		return err
	}
	return err
}

func (r OperatorDto) Serialize(w io.Writer) error {
	return writeOperatorDto(r, w)
}

func (r OperatorDto) Schema() string {
	return "{\"fields\":[{\"default\":null,\"name\":\"Person\",\"type\":[\"null\",{\"fields\":[{\"default\":null,\"name\":\"MRID\",\"type\":[\"null\",\"string\"]}],\"name\":\"PersonDto\",\"type\":\"record\"}]}],\"name\":\"SesamResponseServices.SesamDomainObjects.OperatorDto\",\"type\":\"record\"}"
}

func (r OperatorDto) SchemaName() string {
	return "SesamResponseServices.SesamDomainObjects.OperatorDto"
}

func (_ OperatorDto) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ OperatorDto) SetInt(v int32)       { panic("Unsupported operation") }
func (_ OperatorDto) SetLong(v int64)      { panic("Unsupported operation") }
func (_ OperatorDto) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ OperatorDto) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ OperatorDto) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ OperatorDto) SetString(v string)   { panic("Unsupported operation") }
func (_ OperatorDto) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *OperatorDto) Get(i int) types.Field {
	switch i {
	case 0:
		r.Person = NewUnionNullPersonDto()

		return r.Person
	}
	panic("Unknown field index")
}

func (r *OperatorDto) SetDefault(i int) {
	switch i {
	case 0:
		r.Person = nil
		return
	}
	panic("Unknown field index")
}

func (r *OperatorDto) NullField(i int) {
	switch i {
	case 0:
		r.Person = nil
		return
	}
	panic("Not a nullable field index")
}

func (_ OperatorDto) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ OperatorDto) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ OperatorDto) HintSize(int)                     { panic("Unsupported operation") }
func (_ OperatorDto) Finalize()                        {}

func (_ OperatorDto) AvroCRC64Fingerprint() []byte {
	return []byte(OperatorDtoAvroCRC64Fingerprint)
}

func (r OperatorDto) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["Person"], err = json.Marshal(r.Person)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *OperatorDto) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["Person"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Person); err != nil {
			return err
		}
	} else {
		r.Person = NewUnionNullPersonDto()

		r.Person = nil
	}
	return nil
}
