// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     100486_7.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type OutageDto struct {
	MRID *UnionNullString `json:"MRID"`
}

const OutageDtoAvroCRC64Fingerprint = ";|%Z\x82\xc98\x18"

func NewOutageDto() OutageDto {
	r := OutageDto{}
	r.MRID = nil
	return r
}

func DeserializeOutageDto(r io.Reader) (OutageDto, error) {
	t := NewOutageDto()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeOutageDtoFromSchema(r io.Reader, schema string) (OutageDto, error) {
	t := NewOutageDto()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeOutageDto(r OutageDto, w io.Writer) error {
	var err error
	err = writeUnionNullString(r.MRID, w)
	if err != nil {
		return err
	}
	return err
}

func (r OutageDto) Serialize(w io.Writer) error {
	return writeOutageDto(r, w)
}

func (r OutageDto) Schema() string {
	return "{\"fields\":[{\"default\":null,\"name\":\"MRID\",\"type\":[\"null\",\"string\"]}],\"name\":\"SesamResponseServices.SesamDomainObjects.OutageDto\",\"type\":\"record\"}"
}

func (r OutageDto) SchemaName() string {
	return "SesamResponseServices.SesamDomainObjects.OutageDto"
}

func (_ OutageDto) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ OutageDto) SetInt(v int32)       { panic("Unsupported operation") }
func (_ OutageDto) SetLong(v int64)      { panic("Unsupported operation") }
func (_ OutageDto) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ OutageDto) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ OutageDto) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ OutageDto) SetString(v string)   { panic("Unsupported operation") }
func (_ OutageDto) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *OutageDto) Get(i int) types.Field {
	switch i {
	case 0:
		r.MRID = NewUnionNullString()

		return r.MRID
	}
	panic("Unknown field index")
}

func (r *OutageDto) SetDefault(i int) {
	switch i {
	case 0:
		r.MRID = nil
		return
	}
	panic("Unknown field index")
}

func (r *OutageDto) NullField(i int) {
	switch i {
	case 0:
		r.MRID = nil
		return
	}
	panic("Not a nullable field index")
}

func (_ OutageDto) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ OutageDto) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ OutageDto) HintSize(int)                     { panic("Unsupported operation") }
func (_ OutageDto) Finalize()                        {}

func (_ OutageDto) AvroCRC64Fingerprint() []byte {
	return []byte(OutageDtoAvroCRC64Fingerprint)
}

func (r OutageDto) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["MRID"], err = json.Marshal(r.MRID)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *OutageDto) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["MRID"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.MRID); err != nil {
			return err
		}
	} else {
		r.MRID = NewUnionNullString()

		r.MRID = nil
	}
	return nil
}
