// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     100486_7.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/container"
	"github.com/actgardner/gogen-avro/v10/vm"
)

func NewSwitchActionDtoWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := NewSwitchActionDto()
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

// container reader
type SwitchActionDtoReader struct {
	r io.Reader
	p *vm.Program
}

func NewSwitchActionDtoReader(r io.Reader) (*SwitchActionDtoReader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewSwitchActionDto()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &SwitchActionDtoReader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r SwitchActionDtoReader) Read() (SwitchActionDto, error) {
	t := NewSwitchActionDto()
	err := vm.Eval(r.r, r.p, &t)
	return t, err
}
