// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     100486_7.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

type UnionNullAssetSDtoTypeEnum int

const (
	UnionNullAssetSDtoTypeEnumAssetSDto UnionNullAssetSDtoTypeEnum = 1
)

type UnionNullAssetSDto struct {
	Null      *types.NullVal
	AssetSDto AssetSDto
	UnionType UnionNullAssetSDtoTypeEnum
}

func writeUnionNullAssetSDto(r *UnionNullAssetSDto, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionNullAssetSDtoTypeEnumAssetSDto:
		return writeAssetSDto(r.AssetSDto, w)
	}
	return fmt.Errorf("invalid value for *UnionNullAssetSDto")
}

func NewUnionNullAssetSDto() *UnionNullAssetSDto {
	return &UnionNullAssetSDto{}
}

func (r *UnionNullAssetSDto) Serialize(w io.Writer) error {
	return writeUnionNullAssetSDto(r, w)
}

func DeserializeUnionNullAssetSDto(r io.Reader) (*UnionNullAssetSDto, error) {
	t := NewUnionNullAssetSDto()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func DeserializeUnionNullAssetSDtoFromSchema(r io.Reader, schema string) (*UnionNullAssetSDto, error) {
	t := NewUnionNullAssetSDto()
	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func (r *UnionNullAssetSDto) Schema() string {
	return "[\"null\",{\"fields\":[{\"default\":null,\"name\":\"MRID\",\"type\":[\"null\",\"string\"]}],\"name\":\"AssetSDto\",\"type\":\"record\"}]"
}

func (_ *UnionNullAssetSDto) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *UnionNullAssetSDto) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *UnionNullAssetSDto) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *UnionNullAssetSDto) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullAssetSDto) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *UnionNullAssetSDto) SetString(v string)  { panic("Unsupported operation") }

func (r *UnionNullAssetSDto) SetLong(v int64) {

	r.UnionType = (UnionNullAssetSDtoTypeEnum)(v)
}

func (r *UnionNullAssetSDto) Get(i int) types.Field {

	switch i {
	case 0:
		return r.Null
	case 1:
		r.AssetSDto = NewAssetSDto()
		return &types.Record{Target: (&r.AssetSDto)}
	}
	panic("Unknown field index")
}
func (_ *UnionNullAssetSDto) NullField(i int)                  { panic("Unsupported operation") }
func (_ *UnionNullAssetSDto) HintSize(i int)                   { panic("Unsupported operation") }
func (_ *UnionNullAssetSDto) SetDefault(i int)                 { panic("Unsupported operation") }
func (_ *UnionNullAssetSDto) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullAssetSDto) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *UnionNullAssetSDto) Finalize()                        {}

func (r *UnionNullAssetSDto) MarshalJSON() ([]byte, error) {

	if r == nil {
		return []byte("null"), nil
	}

	switch r.UnionType {
	case UnionNullAssetSDtoTypeEnumAssetSDto:
		return json.Marshal(map[string]interface{}{"SesamResponseServices.SesamDomainObjects.AssetSDto": r.AssetSDto})
	}
	return nil, fmt.Errorf("invalid value for *UnionNullAssetSDto")
}

func (r *UnionNullAssetSDto) UnmarshalJSON(data []byte) error {

	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if len(fields) > 1 {
		return fmt.Errorf("more than one type supplied for union")
	}
	if value, ok := fields["SesamResponseServices.SesamDomainObjects.AssetSDto"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.AssetSDto)
	}
	return fmt.Errorf("invalid value for *UnionNullAssetSDto")
}
