// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     100346_2.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

func writeArrayClosedForInvoicingChange(r []ClosedForInvoicingChange, w io.Writer) error {
	err := vm.WriteLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for _, e := range r {
		err = writeClosedForInvoicingChange(e, w)
		if err != nil {
			return err
		}
	}
	return vm.WriteLong(0, w)
}

type ArrayClosedForInvoicingChangeWrapper struct {
	Target *[]ClosedForInvoicingChange
}

func (_ ArrayClosedForInvoicingChangeWrapper) SetBoolean(v bool)     { panic("Unsupported operation") }
func (_ ArrayClosedForInvoicingChangeWrapper) SetInt(v int32)        { panic("Unsupported operation") }
func (_ ArrayClosedForInvoicingChangeWrapper) SetLong(v int64)       { panic("Unsupported operation") }
func (_ ArrayClosedForInvoicingChangeWrapper) SetFloat(v float32)    { panic("Unsupported operation") }
func (_ ArrayClosedForInvoicingChangeWrapper) SetDouble(v float64)   { panic("Unsupported operation") }
func (_ ArrayClosedForInvoicingChangeWrapper) SetBytes(v []byte)     { panic("Unsupported operation") }
func (_ ArrayClosedForInvoicingChangeWrapper) SetString(v string)    { panic("Unsupported operation") }
func (_ ArrayClosedForInvoicingChangeWrapper) SetUnionElem(v int64)  { panic("Unsupported operation") }
func (_ ArrayClosedForInvoicingChangeWrapper) Get(i int) types.Field { panic("Unsupported operation") }
func (_ ArrayClosedForInvoicingChangeWrapper) AppendMap(key string) types.Field {
	panic("Unsupported operation")
}
func (_ ArrayClosedForInvoicingChangeWrapper) Finalize()        {}
func (_ ArrayClosedForInvoicingChangeWrapper) SetDefault(i int) { panic("Unsupported operation") }
func (r ArrayClosedForInvoicingChangeWrapper) HintSize(s int) {
	if len(*r.Target) == 0 {
		*r.Target = make([]ClosedForInvoicingChange, 0, s)
	}
}
func (r ArrayClosedForInvoicingChangeWrapper) NullField(i int) {
	panic("Unsupported operation")
}

func (r ArrayClosedForInvoicingChangeWrapper) AppendArray() types.Field {
	var v ClosedForInvoicingChange
	v = NewClosedForInvoicingChange()

	*r.Target = append(*r.Target, v)
	return &types.Record{Target: &(*r.Target)[len(*r.Target)-1]}
}
