// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     100366_4.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/container"
	"github.com/actgardner/gogen-avro/v10/vm"
)

func NewSalesOrderUpdatedEventWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := NewSalesOrderUpdatedEvent()
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

// container reader
type SalesOrderUpdatedEventReader struct {
	r io.Reader
	p *vm.Program
}

func NewSalesOrderUpdatedEventReader(r io.Reader) (*SalesOrderUpdatedEventReader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewSalesOrderUpdatedEvent()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &SalesOrderUpdatedEventReader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r SalesOrderUpdatedEventReader) Read() (SalesOrderUpdatedEvent, error) {
	t := NewSalesOrderUpdatedEvent()
	err := vm.Eval(r.r, r.p, &t)
	return t, err
}
