// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     100366_4.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

type UnionNullLocationAddressTypeEnum int

const (
	UnionNullLocationAddressTypeEnumLocationAddress UnionNullLocationAddressTypeEnum = 1
)

type UnionNullLocationAddress struct {
	Null            *types.NullVal
	LocationAddress LocationAddress
	UnionType       UnionNullLocationAddressTypeEnum
}

func writeUnionNullLocationAddress(r *UnionNullLocationAddress, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionNullLocationAddressTypeEnumLocationAddress:
		return writeLocationAddress(r.LocationAddress, w)
	}
	return fmt.Errorf("invalid value for *UnionNullLocationAddress")
}

func NewUnionNullLocationAddress() *UnionNullLocationAddress {
	return &UnionNullLocationAddress{}
}

func (r *UnionNullLocationAddress) Serialize(w io.Writer) error {
	return writeUnionNullLocationAddress(r, w)
}

func DeserializeUnionNullLocationAddress(r io.Reader) (*UnionNullLocationAddress, error) {
	t := NewUnionNullLocationAddress()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func DeserializeUnionNullLocationAddressFromSchema(r io.Reader, schema string) (*UnionNullLocationAddress, error) {
	t := NewUnionNullLocationAddress()
	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func (r *UnionNullLocationAddress) Schema() string {
	return "[\"null\",{\"fields\":[{\"default\":null,\"name\":\"AddressFreeForm\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"City\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"CountryCode\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"HouseNumber\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"MunicipalityId\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"PropertyUnitNumber\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"StreetName\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"ZipCode\",\"type\":[\"null\",\"string\"]}],\"name\":\"LocationAddress\",\"type\":\"record\"}]"
}

func (_ *UnionNullLocationAddress) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *UnionNullLocationAddress) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *UnionNullLocationAddress) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *UnionNullLocationAddress) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullLocationAddress) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *UnionNullLocationAddress) SetString(v string)  { panic("Unsupported operation") }

func (r *UnionNullLocationAddress) SetLong(v int64) {

	r.UnionType = (UnionNullLocationAddressTypeEnum)(v)
}

func (r *UnionNullLocationAddress) Get(i int) types.Field {

	switch i {
	case 0:
		return r.Null
	case 1:
		r.LocationAddress = NewLocationAddress()
		return &types.Record{Target: (&r.LocationAddress)}
	}
	panic("Unknown field index")
}
func (_ *UnionNullLocationAddress) NullField(i int)                  { panic("Unsupported operation") }
func (_ *UnionNullLocationAddress) HintSize(i int)                   { panic("Unsupported operation") }
func (_ *UnionNullLocationAddress) SetDefault(i int)                 { panic("Unsupported operation") }
func (_ *UnionNullLocationAddress) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullLocationAddress) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *UnionNullLocationAddress) Finalize()                        {}

func (r *UnionNullLocationAddress) MarshalJSON() ([]byte, error) {

	if r == nil {
		return []byte("null"), nil
	}

	switch r.UnionType {
	case UnionNullLocationAddressTypeEnumLocationAddress:
		return json.Marshal(map[string]interface{}{"Afiextensions.Schemas.SalesOrderEvents.V1.LocationAddress": r.LocationAddress})
	}
	return nil, fmt.Errorf("invalid value for *UnionNullLocationAddress")
}

func (r *UnionNullLocationAddress) UnmarshalJSON(data []byte) error {

	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if len(fields) > 1 {
		return fmt.Errorf("more than one type supplied for union")
	}
	if value, ok := fields["Afiextensions.Schemas.SalesOrderEvents.V1.LocationAddress"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.LocationAddress)
	}
	return fmt.Errorf("invalid value for *UnionNullLocationAddress")
}
