// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     100366_4.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

type UnionNullOrderSupplierTypeEnum int

const (
	UnionNullOrderSupplierTypeEnumOrderSupplier UnionNullOrderSupplierTypeEnum = 1
)

type UnionNullOrderSupplier struct {
	Null          *types.NullVal
	OrderSupplier OrderSupplier
	UnionType     UnionNullOrderSupplierTypeEnum
}

func writeUnionNullOrderSupplier(r *UnionNullOrderSupplier, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionNullOrderSupplierTypeEnumOrderSupplier:
		return writeOrderSupplier(r.OrderSupplier, w)
	}
	return fmt.Errorf("invalid value for *UnionNullOrderSupplier")
}

func NewUnionNullOrderSupplier() *UnionNullOrderSupplier {
	return &UnionNullOrderSupplier{}
}

func (r *UnionNullOrderSupplier) Serialize(w io.Writer) error {
	return writeUnionNullOrderSupplier(r, w)
}

func DeserializeUnionNullOrderSupplier(r io.Reader) (*UnionNullOrderSupplier, error) {
	t := NewUnionNullOrderSupplier()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func DeserializeUnionNullOrderSupplierFromSchema(r io.Reader, schema string) (*UnionNullOrderSupplier, error) {
	t := NewUnionNullOrderSupplier()
	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func (r *UnionNullOrderSupplier) Schema() string {
	return "[\"null\",{\"fields\":[{\"default\":null,\"name\":\"FromDate\",\"type\":[\"null\",\"string\"]},{\"name\":\"HourlyRead\",\"type\":\"boolean\"},{\"default\":null,\"name\":\"SettlementMethod\",\"type\":[\"null\",\"string\"]},{\"default\":null,\"name\":\"SupplierId\",\"type\":[\"null\",\"int\"]},{\"default\":null,\"name\":\"ToDate\",\"type\":[\"null\",\"string\"]}],\"name\":\"OrderSupplier\",\"type\":\"record\"}]"
}

func (_ *UnionNullOrderSupplier) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *UnionNullOrderSupplier) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *UnionNullOrderSupplier) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *UnionNullOrderSupplier) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionNullOrderSupplier) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *UnionNullOrderSupplier) SetString(v string)  { panic("Unsupported operation") }

func (r *UnionNullOrderSupplier) SetLong(v int64) {

	r.UnionType = (UnionNullOrderSupplierTypeEnum)(v)
}

func (r *UnionNullOrderSupplier) Get(i int) types.Field {

	switch i {
	case 0:
		return r.Null
	case 1:
		r.OrderSupplier = NewOrderSupplier()
		return &types.Record{Target: (&r.OrderSupplier)}
	}
	panic("Unknown field index")
}
func (_ *UnionNullOrderSupplier) NullField(i int)                  { panic("Unsupported operation") }
func (_ *UnionNullOrderSupplier) HintSize(i int)                   { panic("Unsupported operation") }
func (_ *UnionNullOrderSupplier) SetDefault(i int)                 { panic("Unsupported operation") }
func (_ *UnionNullOrderSupplier) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionNullOrderSupplier) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *UnionNullOrderSupplier) Finalize()                        {}

func (r *UnionNullOrderSupplier) MarshalJSON() ([]byte, error) {

	if r == nil {
		return []byte("null"), nil
	}

	switch r.UnionType {
	case UnionNullOrderSupplierTypeEnumOrderSupplier:
		return json.Marshal(map[string]interface{}{"Afiextensions.Schemas.SalesOrderEvents.V1.OrderSupplier": r.OrderSupplier})
	}
	return nil, fmt.Errorf("invalid value for *UnionNullOrderSupplier")
}

func (r *UnionNullOrderSupplier) UnmarshalJSON(data []byte) error {

	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if len(fields) > 1 {
		return fmt.Errorf("more than one type supplied for union")
	}
	if value, ok := fields["Afiextensions.Schemas.SalesOrderEvents.V1.OrderSupplier"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.OrderSupplier)
	}
	return fmt.Errorf("invalid value for *UnionNullOrderSupplier")
}
