// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     100443_1.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/container"
	"github.com/actgardner/gogen-avro/v10/vm"
)

func NewInvoicePostedWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := NewInvoicePosted()
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

// container reader
type InvoicePostedReader struct {
	r io.Reader
	p *vm.Program
}

func NewInvoicePostedReader(r io.Reader) (*InvoicePostedReader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewInvoicePosted()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &InvoicePostedReader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r InvoicePostedReader) Read() (InvoicePosted, error) {
	t := NewInvoicePosted()
	err := vm.Eval(r.r, r.p, &t)
	return t, err
}
